/** POIs as percent from the top-left of the full Maggot/wiki JPEG (including legends).
 *  mx/my sit on the terrain feature, not the Maggot/wiki text banner beside it.
 *  Banner ABOVE feature → increase my (south). Banner BELOW feature → decrease my (north). */

module.exports.seedPois = [
  // Night Harbor — Maggot V5 percents stamped on night-harbor.jpg labels
  { id: "nh-west-gate", zoneId: "night-harbor", name: "West Gate", kind: "landmark", mx: 23.5, my: 52.0, notes: "Gate arch opening in the west wall. Out to Shaded Dunes." },
  { id: "nh-north-gate", zoneId: "night-harbor", name: "North Gate", kind: "landmark", mx: 72.0, my: 32.5, notes: "North wall gate opening, south of the banner. Out to Sungreet Strand." },
  { id: "nh-twilight-harbor", zoneId: "night-harbor", name: "Twilight Harbor", kind: "dock", mx: 52.0, my: 72.0, notes: "Stone promenade / pier heads (banner sits in the water below)." },
  { id: "nh-palace", zoneId: "night-harbor", name: "Palace", kind: "landmark", mx: 77.2, my: 48.2, notes: "Gold dome, east city." },
  { id: "nh-night-market", zoneId: "night-harbor", name: "Night Market", kind: "vendor", mx: 37.5, my: 52.5, notes: "Bags, cloth/chain/plate, used weapons, grocer, cobbler, herbs, general goods." },
  { id: "nh-saltbreeze", zoneId: "night-harbor", name: "Saltbreeze Park", kind: "camp", mx: 51.5, my: 48.5, soloMin: 1, soloMax: 5, monsters: "Bats", notes: "Park greenery, south of the banner. Bats at night." },
  { id: "nh-sageside", zoneId: "night-harbor", name: "Sageside", kind: "vendor", mx: 68.5, my: 34.0, notes: "Just inside North Gate. General goods, used armor, bags, food, leatherworker." },
  { id: "nh-blackleather", zoneId: "night-harbor", name: "Blackleather Bazaar", kind: "vendor", mx: 62.0, my: 24.0, notes: "Used armor/weapons, butcher & cook, fish trader. Market alcove south of the banner." },
  { id: "nh-little-hall", zoneId: "night-harbor", name: "Little Half Town", kind: "vendor", mx: 52.0, my: 60.5, notes: "Building block west of the Palace / north of Twilight Harbor." },
  { id: "nh-sojourner", zoneId: "night-harbor", name: "Sojourner's Camp", kind: "camp", mx: 28.5, my: 34.5, soloMin: 1, soloMax: 6, notes: "Campfire / tent yard west of the Arena, east of Hospice. Hult's fire is just north." },
  { id: "nh-zl-dunes", zoneId: "night-harbor", name: "Zoneline: Shaded Dunes", kind: "zoneline", mx: 2.5, my: 52.0 },
  { id: "nh-zl-wyrmsbane", zoneId: "night-harbor", name: "Zoneline: Tomb of the Last Wyrmsbane", kind: "zoneline", mx: 10.0, my: 29.2, notes: "Maggot: to Wyrmsbane Tomb." },
  { id: "nh-zl-sungreet", zoneId: "night-harbor", name: "Zoneline: Sungreet Strand", kind: "zoneline", mx: 71.0, my: 5.0, notes: "North road exit at map edge." },
  { id: "nh-west-yards", zoneId: "night-harbor", name: "West gate yards", kind: "camp", mx: 16.0, my: 51.0, soloMin: 1, soloMax: 5, monsters: "Rats, bats, snakes, beetles, Ashira" },
  { id: "nh-north-yards", zoneId: "night-harbor", name: "North gate yards", kind: "camp", mx: 72.5, my: 28.5, soloMin: 1, soloMax: 5, monsters: "Rats, bats, snakes, spiders, skeletons" },
  { id: "nh-crocs", zoneId: "night-harbor", name: "West gate shoreline crocs", kind: "camp", mx: 14.0, my: 57.0, soloMin: 4, soloMax: 7, groupMin: 3, groupMax: 6, monsters: "Crocodile hatchlings", notes: "Non-hostile. Named Snar the Egg Collector." },
  { id: "nh-boatyard", zoneId: "night-harbor", name: "Steel Talon Naval Base", kind: "camp", mx: 30.5, my: 68.0, soloMin: 1, soloMax: 5, monsters: "Rats" },
  { id: "nh-goblins", zoneId: "night-harbor", name: "Twilight Harbor goblins", kind: "camp", mx: 54.0, my: 73.0, soloMin: 13, soloMax: 15, groupMin: 8, groupMax: 12, monsters: "Goblins", notes: "By the cranes. Social, no faction hit." },
  { id: "nh-graveyard", zoneId: "night-harbor", name: "Night Harbor Crypt", kind: "camp", mx: 52.5, my: 36.5, soloMin: 12, soloMax: 16, groupMin: 10, groupMax: 14, monsters: "Undead", notes: "Need a key. They come out at night." },
  { id: "nh-shaded-bloom", zoneId: "night-harbor", name: "Shaded Bloom Inn", kind: "landmark", mx: 31.5, my: 41.0, notes: "Inn courtyard south of Sojourner's Camp (banner above). Basement beetles/rats 1–3." },
  { id: "nh-necropolis", zoneId: "night-harbor", name: "Necropolis front yard", kind: "camp", mx: 56.5, my: 30.0, soloMin: 1, soloMax: 8, monsters: "Rats, bats, spiders, skeletons, SK trainees", notes: "Yard south of Concourse of Souls. Night Terror at night." },

  { id: "nh-steel-talons", zoneId: "night-harbor", name: "Steel Talons Academy", kind: "quest", mx: 23.5, my: 60.5, notes: "Turn-in: Fedamius Steele III, Lurinda Steele, Elrind Steele, Jacobin Yeats. Maggot ARC/FTR/RNG courtyard." },
  { id: "nh-foss-wall", zoneId: "night-harbor", name: "Foss Dunestrider (west wall)", kind: "quest", mx: 23.0, my: 50.5, notes: "Turn-in: Foss Dunestrider. Ranger. Atop the wall at West Gate." },
  { id: "nh-fourfold", zoneId: "night-harbor", name: "School of the Fourfold Path", kind: "quest", mx: 54.0, my: 61.5, notes: "Turn-in: Chahaya Tam (Monk), Tenebrim Tam & Pedram (Elementalist). Maggot ELE/MNK, east of Little Half Town." },
  { id: "nh-wizard-tower", zoneId: "night-harbor", name: "Wizard tower (Sageside)", kind: "quest", mx: 82.0, my: 35.5, notes: "Turn-in: Olvin Viscus, Lanna Ivintoria, Jabir Ilhamar. Maggot WIZ." },
  { id: "nh-hospice", zoneId: "night-harbor", name: "Wayfarer's Hospice", kind: "quest", mx: 25.0, my: 38.5, notes: "Turn-in: Millicent Domaire, Thibald Burlond, Jiselle Heyley, Trey Fulton, Halrinn Grimsul. Maggot Hospice CLR/PAL building." },
  { id: "nh-concourse", zoneId: "night-harbor", name: "Concourse of Souls", kind: "quest", mx: 55.5, my: 26.5, notes: "Turn-in: Exavius Deathwhisper, Brazzic Durraim, Buckmarr Gorstagg, Marvion Hallows, Sekhmet. Maggot NEC/SHD." },
  { id: "nh-illuminators", zoneId: "night-harbor", name: "Illuminators' Guild", kind: "quest", mx: 36.5, my: 59.0, notes: "Turn-in: Sinastin Aspenleaf, Albrecht, Irfan Raz. Maggot ROG by Shrine to Forbor." },
  { id: "nh-azure-veils", zoneId: "night-harbor", name: "Azure Veils / Jamee Langris", kind: "quest", mx: 32.0, my: 53.5, notes: "Turn-in: Jamee Langris (Bard). Maggot BRD, between Bathhouse and Night Market." },
  { id: "nh-circle-rains", zoneId: "night-harbor", name: "Circle of Scarce Rains", kind: "quest", mx: 58.5, my: 52.0, notes: "Turn-in: Rolan Talmula, Calaada, Aaliyah. Maggot DRU, east of Saltbreeze." },
  { id: "nh-seekers", zoneId: "night-harbor", name: "Seekers of the Lost Eye", kind: "quest", mx: 58.0, my: 45.0, notes: "Turn-in: Errol Shrewtender, Masoumeh Akhtar, Eskander Akhtar. Maggot BST/SHM, north of Saltbreeze." },
  { id: "nh-spellbinders", zoneId: "night-harbor", name: "Spellbinders Spire", kind: "quest", mx: 82.5, my: 33.0, notes: "Turn-in: Jaffar Jhaym, Njau Hansou, Petra Gyle. Maggot ENC/INQ/SPB temples." },
  { id: "nh-enchanter", zoneId: "night-harbor", name: "Enchanter registry", kind: "quest", mx: 66.0, my: 29.5, notes: "Turn-in: Registrar Vauquelin, Master Wincog. Between Concourse and North Gate." },
  { id: "nh-hult", zoneId: "night-harbor", name: "Hult Beetlewrangler", kind: "quest", mx: 29.0, my: 32.0, notes: "Turn-in: Scarab armor and Cinder shield/varnish. Campfire under Temple to Eltindra, north of Sojourner's Camp. Not the Arena." },
  { id: "nh-blacksmith", zoneId: "night-harbor", name: "Master blacksmith (night)", kind: "quest", mx: 37.5, my: 52.5, notes: "Turn-in: Cinder Beetle Boots. Night Market, spawns 6 PM." },
  { id: "nh-sielah", zoneId: "night-harbor", name: "Weaponsmith Sielah Zefir", kind: "quest", mx: 62.0, my: 24.0, notes: "Turn-in: Cinder Beetle Helm. Blackleather Bazaar." },
  { id: "nh-tannery", zoneId: "night-harbor", name: "Tannery (Dilshad)", kind: "quest", mx: 37.0, my: 37.5, notes: "Turn-in: Cinder tanning agent. Maggot Tannery building, south of the Arena." },
  { id: "nh-benlink", zoneId: "night-harbor", name: "Shipwright Benlink", kind: "quest", mx: 28.0, my: 70.0, notes: "Turn-in: Cinder Beetle Greaves. Steel Talon Naval Base crates." },
  { id: "nh-huda", zoneId: "night-harbor", name: "Master Shipwright Huda", kind: "quest", mx: 71.0, my: 64.0, notes: "Turn-in: Cinder Beetle Breastplate. Docks south of Teleporter to Sageside." },
  { id: "nh-witcher", zoneId: "night-harbor", name: "Witcher Sayyaad", kind: "quest", mx: 55.5, my: 28.0, notes: "Turn-in: Night Terror wing / fur / head. Concourse of Souls entrance." },
  { id: "nh-holt", zoneId: "night-harbor", name: "Lt. Jarovik Holt / Theodora", kind: "quest", mx: 82.0, my: 61.5, notes: "Turn-in: Platinum Badge of the Living City. Maggot The Bends, east docks." },

  { id: "nh-sewers", zoneId: "night-harbor", name: "Sewers entrance", kind: "dungeon", mx: 54.0, my: 59.5, notes: "Tunnel mouth north of the to-Sewers banner." },
  { id: "nh-library", zoneId: "night-harbor", name: "Library", kind: "landmark", mx: 82.0, my: 37.5, notes: "Library building in Sageside, not the WIZ banner." },
  { id: "nh-bank", zoneId: "night-harbor", name: "West-gate bank", kind: "vendor", mx: 26.5, my: 51.5, notes: "Inside West Gate by the Bathhouse." },
  { id: "nh-garrison", zoneId: "night-harbor", name: "Steel Talon Garrison", kind: "landmark", mx: 23.0, my: 66.0, notes: "SW fort. Temple to Haradrel in the yard." },
  { id: "nh-mage-tower", zoneId: "night-harbor", name: "Mage tower", kind: "trainer", mx: 82.0, my: 35.5, notes: "Maggot WIZ spire in Sageside." },
  { id: "nh-eltindra", zoneId: "night-harbor", name: "Temple of Eltindra", kind: "landmark", mx: 30.5, my: 30.5, notes: "Temple building immediately north of Sojourner's Camp." },
  { id: "nh-guild-hall", zoneId: "night-harbor", name: "Great Guild Hall", kind: "landmark", mx: 54.0, my: 44.0, notes: "Building north of Saltbreeze Park." },
  { id: "nh-fishing", zoneId: "night-harbor", name: "Fishing dock", kind: "vendor", mx: 54.0, my: 73.0, notes: "Twilight Harbor pier boards." },
  { id: "nh-arena", zoneId: "night-harbor", name: "Arena", kind: "landmark", mx: 40.0, my: 29.5, notes: "Center of the arena floor (banner north of the structure)." },
  { id: "nh-bathhouse", zoneId: "night-harbor", name: "Bathhouse", kind: "landmark", mx: 27.5, my: 52.0, notes: "East of West Gate, by the bank — pool building, not the banner." },
  { id: "nh-bends", zoneId: "night-harbor", name: "The Bends", kind: "landmark", mx: 82.0, my: 61.5, notes: "East docks. Holt / Theodora." },
  { id: "nh-tele-sageside", zoneId: "night-harbor", name: "Teleporter to Sageside", kind: "landmark", mx: 70.5, my: 59.0, notes: "Blue portal pad south of the Palace." },
  { id: "nh-haradrel", zoneId: "night-harbor", name: "Temple to Haradrel", kind: "landmark", mx: 24.0, my: 66.5, notes: "Maggot: Steel Talon Garrison yard." },
  { id: "nh-forbor", zoneId: "night-harbor", name: "Shrine to Forbor", kind: "landmark", mx: 36.0, my: 59.0, notes: "Maggot ROG shrine, Illuminators' Guild." },

  // Shaded Dunes — pins sit on the terrain, not the Maggot banners
  { id: "sd-zl-harbor", zoneId: "shaded-dunes", name: "Zoneline: Night Harbor", kind: "zoneline", mx: 95.2, my: 39.2, notes: "East path off the dunes, not the banner." },
  { id: "sd-zl-telekir", zoneId: "shaded-dunes", name: "Zoneline: Tel Ekir", kind: "zoneline", mx: 13.8, my: 17.6, notes: "NW canyon path mouth, below the title scroll." },
  { id: "sd-zl-fallen", zoneId: "shaded-dunes", name: "Zoneline: Fallen Pass", kind: "zoneline", mx: 4.8, my: 37.2, notes: "West path off the cliff edge." },
  { id: "sd-zl-ancient", zoneId: "shaded-dunes", name: "Zoneline: Ancient Crypt", kind: "dungeon", mx: 59.5, my: 23.5, notes: "North-wall crypt gate, not the title banner." },
  { id: "sd-zl-irem", zoneId: "shaded-dunes", name: "Zoneline: Caves of Irem", kind: "dungeon", mx: 22.8, my: 56.0, notes: "Cave mouth in the west cliff." },
  { id: "sd-zl-infested", zoneId: "shaded-dunes", name: "Zoneline: Infested Crypt", kind: "dungeon", mx: 27.2, my: 62.8, notes: "Crypt door SE of Irem rock." },
  { id: "sd-crypt-ruins", zoneId: "shaded-dunes", name: "Crypt Ruins", kind: "camp", mx: 61.0, my: 31.5, groupMin: 6, groupMax: 12, monsters: "Undead", notes: "Stone wall foundations north of the Crypt Ruins banner." },
  { id: "sd-oasis", zoneId: "shaded-dunes", name: "Oasis Island", kind: "named", mx: 39.5, my: 63.2, notes: "Tan island in the west oasis lake, south of the Maggot banner. Yezkiel the Gatekeeper ~20+." },
  { id: "sd-undead-ruins", zoneId: "shaded-dunes", name: "Undead Ruins", kind: "camp", mx: 53.5, my: 58.5, soloMin: 8, soloMax: 10, monsters: "Skeletons, zombies", notes: "Stone foundations SE of Oasis Island, under the Undead Ruins banner." },
  { id: "sd-ashira-oasis", zoneId: "shaded-dunes", name: "Ashira Oasis Camp", kind: "camp", mx: 72.0, my: 56.5, groupMin: 6, groupMax: 10, monsters: "Ashira", notes: "Palm oasis east of Undead Ruins (banner sits below the grove). Dhajr Spitemaw named." },
  { id: "sd-mercenary", zoneId: "shaded-dunes", name: "Mercenary Camp", kind: "camp", mx: 84.5, my: 54.0, groupMin: 6, groupMax: 12, monsters: "Mercenaries / bandits", notes: "Far-east palm oasis (banner sits above the grove)." },
  { id: "sd-smugglers", zoneId: "shaded-dunes", name: "Smugglers Camp", kind: "camp", mx: 25.0, my: 80.5, soloMin: 8, soloMax: 12, groupMin: 6, groupMax: 10, monsters: "Smugglers, wererats", notes: "SW river-mouth camp on shore, not the water. Wererats at night. Named Toma the Two-Faced." },
  { id: "sd-dock", zoneId: "shaded-dunes", name: "Docks", kind: "dock", mx: 91.5, my: 76.0, notes: "SE wooden pier at the waterline." },
  { id: "sd-ashira-ekir", zoneId: "shaded-dunes", name: "Ashira near Tel Ekir line", kind: "camp", mx: 16.5, my: 22.5, groupMin: 6, groupMax: 10, monsters: "Ashira", notes: "NW canyon grove under the Tel Ekir path." },
  { id: "sd-crocs", zoneId: "shaded-dunes", name: "Coastal crocs", kind: "camp", mx: 78.5, my: 76.5, soloMin: 5, soloMax: 8, monsters: "Crocodiles, caimans", notes: "South shore toward the docks. Watch for Chompers ~16." },
  { id: "sd-cheikho", zoneId: "shaded-dunes", name: "Cheikho (croc hunters)", kind: "quest", mx: 80.5, my: 77.5, notes: "Turn-in: Chomper's Hide for Chompers' Hide Tunic. South shore near dock camp." },
  { id: "sd-ground-sewer", zoneId: "shaded-dunes", name: "Ground sewer", kind: "landmark", mx: 53.5, my: 66.5, notes: "Grate south of Undead Ruins." },
  { id: "sd-lookout", zoneId: "shaded-dunes", name: "North canyon lookout", kind: "landmark", mx: 18.5, my: 24.5 },

  // Sungreet Strand — Maggot banners
  { id: "ss-zl-harbor", zoneId: "sungreet-strand", name: "Zoneline: Night Harbor", kind: "zoneline", mx: 2.0, my: 56.0, notes: "West fence gap into Night Harbor." },
  { id: "ss-zl-ekir", zoneId: "sungreet-strand", name: "Zoneline: Tel Ekir", kind: "zoneline", mx: 87.5, my: 5.0 },
  { id: "ss-zl-flats", zoneId: "sungreet-strand", name: "Zoneline: Glass Flats", kind: "zoneline", mx: 98.0, my: 39.0 },
  { id: "ss-tunnels", zoneId: "sungreet-strand", name: "Tunnels", kind: "dungeon", mx: 60.5, my: 17.0, notes: "North cave mouth in the cliff (banner below / beside)." },
  { id: "ss-researchers", zoneId: "sungreet-strand", name: "Researchers", kind: "landmark", mx: 38.5, my: 29.5, notes: "Tent camp against the north cliff, south of the banner." },
  { id: "ss-skeleton", zoneId: "sungreet-strand", name: "Skeleton Camp", kind: "camp", mx: 49.5, my: 42.5, groupMin: 8, groupMax: 14, monsters: "Skeletons", notes: "Skintakers ruin square, south of the banner." },
  { id: "ss-quarry", zoneId: "sungreet-strand", name: "Quarry", kind: "camp", mx: 60.0, my: 32.0, soloMin: 20, soloMax: 28, groupMin: 16, groupMax: 23, monsters: "Cinder workers, goblins", notes: "Excavated pit north of the Quarry banner. Cinder Beetle armor quests." },
  { id: "ss-stonehammer", zoneId: "sungreet-strand", name: "Foreman Stonehammer", kind: "quest", mx: 61.0, my: 31.0, notes: "Turn-in: Order for Selenite + Battered Canteen (Shaman becoming)." },
  { id: "ss-almina", zoneId: "sungreet-strand", name: "Almina Weepingwind (druid ring)", kind: "quest", mx: 50.0, my: 75.0, notes: "Turn-in: Druid water-plague chain. South coast standing stones / grove." },
  { id: "ss-tig", zoneId: "sungreet-strand", name: "Tig", kind: "quest", mx: 40.5, my: 52.0, notes: "Turn-in: Tig's Measuring Quest. Central ruins." },
  { id: "ss-pirate-tavern", zoneId: "sungreet-strand", name: "River Pirate Tavern", kind: "camp", mx: 63.5, my: 66.5, soloMin: 26, soloMax: 32, groupMin: 22, groupMax: 28, monsters: "Pirates, hired trackers", notes: "Shore building north of the tavern banner (banner sits below)." },
  { id: "ss-ashira-tents", zoneId: "sungreet-strand", name: "Ashira tent camps", kind: "camp", mx: 22.5, my: 50.0, soloMin: 5, soloMax: 10, groupMin: 4, groupMax: 8, monsters: "Ashira", notes: "Ruin walls / tents." },
  { id: "ss-beach", zoneId: "sungreet-strand", name: "Beach thugs & acolytes", kind: "camp", mx: 35.0, my: 76.0, soloMin: 12, soloMax: 16, groupMin: 8, groupMax: 12, monsters: "Thugs, acolytes", notes: "High damage — tank and healer." },
  { id: "ss-farms", zoneId: "sungreet-strand", name: "Agricole farms", kind: "landmark", mx: 28.5, my: 53.0, notes: "Third building hides Grain Cellar (double-click wall)." },
  { id: "ss-ashira-flats", zoneId: "sungreet-strand", name: "Ashira by Glass Flats line", kind: "camp", mx: 86.0, my: 38.0, soloMin: 21, soloMax: 26, groupMin: 18, groupMax: 23, monsters: "Ashira" },
  { id: "ss-grain-cellar", zoneId: "sungreet-strand", name: "Grain Cellar wall", kind: "dungeon", mx: 29.5, my: 53.5, notes: "Third farm building — double-click the wall." },
  { id: "ss-druid-stones", zoneId: "sungreet-strand", name: "Standing stones (druid)", kind: "landmark", mx: 50.0, my: 76.0 },
  { id: "ss-caves-north", zoneId: "sungreet-strand", name: "North caves", kind: "dungeon", mx: 60.5, my: 17.5 },
  { id: "ss-east-grove", zoneId: "sungreet-strand", name: "East grove named", kind: "named", mx: 85.5, my: 52.0, notes: "Palm grove on the Glass Flats side." },
  { id: "ss-south-isle", zoneId: "sungreet-strand", name: "South river isle", kind: "camp", mx: 64.0, my: 82.0, soloMin: 12, soloMax: 18, monsters: "Beach fauna" },
  { id: "ss-druids-east", zoneId: "sungreet-strand", name: "East druid trees", kind: "camp", mx: 76.0, my: 55.0, groupMin: 20, groupMax: 28, monsters: "Druids / named", notes: "Palm grove / rock feature east of the quarry road." },
  { id: "ss-west-ashira", zoneId: "sungreet-strand", name: "West road Ashira", kind: "camp", mx: 10.5, my: 43.0, soloMin: 5, soloMax: 10, monsters: "Ashira", notes: "Cyan Maggot dots on the Night Harbor road." },

  // Fallen Pass — Maggot
  { id: "fp-zl-zintar", zoneId: "fallen-pass", name: "Zoneline: Vale of Zintar", kind: "zoneline", mx: 44.0, my: 4.0 },
  { id: "fp-zl-dunes", zoneId: "fallen-pass", name: "Zoneline: Shaded Dunes", kind: "zoneline", mx: 95.0, my: 22.0 },
  { id: "fp-hidden", zoneId: "fallen-pass", name: "Hidden Pass", kind: "landmark", mx: 22.0, my: 22.0 },
  { id: "fp-red-mantle", zoneId: "fallen-pass", name: "Red Mantle Camp", kind: "camp", mx: 34.0, my: 26.0, groupMin: 20, groupMax: 28, monsters: "Red Mantle", notes: "Tent cluster south of the Red Mantle banner." },
  { id: "fp-watch", zoneId: "fallen-pass", name: "Fallen Watch fort", kind: "landmark", mx: 78.0, my: 60.0, notes: "Fort courtyard square, south of the Fallen Watch banner." },
  { id: "fp-smuggler-caves", zoneId: "fallen-pass", name: "Smugglers Caves", kind: "dungeon", mx: 42.0, my: 71.0, notes: "Cave mouth in the rock (banner sits below — pin north of banner)." },
  { id: "fp-rat-caves", zoneId: "fallen-pass", name: "Rat Caves / Skri'Var", kind: "camp", mx: 13.0, my: 46.5, soloMin: 38, soloMax: 44, groupMin: 34, groupMax: 38, monsters: "Skri'Var rats", notes: "West cliff cave mouth. Many named." },
  { id: "fp-pit", zoneId: "fallen-pass", name: "Pit dusty skeletons", kind: "camp", mx: 54.0, my: 41.0, soloMin: 17, soloMax: 20, groupMin: 15, groupMax: 19, monsters: "Dusty skeletons 16–19", notes: "Circular green pit. Don't go up the ramp. Easy singles along the wall." },
  { id: "fp-beetles", zoneId: "fallen-pass", name: "Pit bone carver beetles", kind: "camp", mx: 56.0, my: 46.0, soloMin: 25, soloMax: 27, groupMin: 20, groupMax: 25, monsters: "Bone carver beetles", notes: "Named Necroferius." },
  { id: "fp-ghouls", zoneId: "fallen-pass", name: "Ramp skeletons & ghouls", kind: "camp", mx: 60.0, my: 48.0, soloMin: 26, soloMax: 28, groupMin: 20, groupMax: 25, monsters: "Skeletons, ghouls", notes: "Ghoul adepts nuke ~200 blaze." },
  { id: "fp-plagueborn", zoneId: "fallen-pass", name: "Plagueborn undead", kind: "camp", mx: 64.0, my: 44.0, soloMin: 36, soloMax: 42, groupMin: 30, groupMax: 35, monsters: "Plagueborn undead" },
  { id: "fp-watch-door", zoneId: "fallen-pass", name: "Into Fallen Watch", kind: "dungeon", mx: 76.0, my: 58.0, notes: "Fort gate / door." },
  { id: "fp-rat-cave-trail", zoneId: "fallen-pass", name: "Rat Cave (trail)", kind: "dungeon", mx: 57.0, my: 36.0, notes: "Cave mouth on the dunes path, south of its banner." },
  { id: "fp-west-wall", zoneId: "fallen-pass", name: "West wall camps", kind: "camp", mx: 18.0, my: 30.0, soloMin: 16, soloMax: 22, monsters: "Undead, pass trash" },
  { id: "fp-dunes-approach", zoneId: "fallen-pass", name: "Dunes approach camps", kind: "camp", mx: 80.0, my: 24.0, soloMin: 8, soloMax: 16, monsters: "Desert fauna", notes: "Camps toward the Shaded Dunes line." },
  { id: "fp-watch-yard", zoneId: "fallen-pass", name: "Fallen Watch yard", kind: "camp", mx: 70.0, my: 56.0, groupMin: 20, groupMax: 28, monsters: "Undead", notes: "Yard west of the fort." },
  { id: "fp-smuggler-camp", zoneId: "fallen-pass", name: "Smugglers Caves yard", kind: "camp", mx: 40.0, my: 68.0, soloMin: 12, soloMax: 18, monsters: "Smugglers" },

  // Glass Flats — wiki schematic
  { id: "gf-goblins", zoneId: "glass-flats", name: "Goblin bone field", kind: "camp", mx: 20.8, my: 28.5, soloMin: 18, soloMax: 22, groupMin: 16, groupMax: 20, monsters: "Goblins", notes: "West bone piles." },
  { id: "gf-vipers", zoneId: "glass-flats", name: "Beach vipers & beetles", kind: "camp", mx: 48.0, my: 61.5, soloMin: 24, soloMax: 28, groupMin: 20, groupMax: 25, monsters: "Szuurian vipers, beetles" },
  { id: "gf-cultists", zoneId: "glass-flats", name: "Crystal cultists", kind: "camp", mx: 82.5, my: 21.8, soloMin: 46, soloMax: 52, groupMin: 42, groupMax: 48, monsters: "Cultists", notes: "NE crystal field by the black pit." },
  { id: "gf-tower", zoneId: "glass-flats", name: "Obsidian tower", kind: "camp", mx: 37.5, my: 48.0, groupMin: 51, groupMax: 60, monsters: "Undead, cultists", notes: "Black tower base, west-center." },
  { id: "gf-zl-vale", zoneId: "glass-flats", name: "Zoneline: Vale of Zintar", kind: "zoneline", mx: 3.2, my: 45.0 },
  { id: "gf-zl-sungreet", zoneId: "glass-flats", name: "Zoneline: Sungreet Strand", kind: "zoneline", mx: 78.6, my: 92.4 },
  { id: "gf-sw-ruin", zoneId: "glass-flats", name: "Southwest ruin", kind: "landmark", mx: 9.3, my: 77.8 },
  { id: "gf-crystals-east", zoneId: "glass-flats", name: "East crystal shore", kind: "landmark", mx: 88.0, my: 47.0 },
  { id: "gf-crystal-pit", zoneId: "glass-flats", name: "Northeast crystal pit", kind: "camp", mx: 83.5, my: 16.5, soloMin: 46, soloMax: 52, monsters: "Cultists", notes: "Black square in the NE crystal field." },
  { id: "gf-south-camp", zoneId: "glass-flats", name: "South trail camp", kind: "camp", mx: 63.8, my: 78.0, soloMin: 24, soloMax: 30, monsters: "Vipers, beetles" },

  // Vale of Zintar
  { id: "vz-ashira", zoneId: "vale-of-zintar", name: "Corrupted Ashira lake tents", kind: "camp", mx: 66.0, my: 66.0, soloMin: 30, soloMax: 32, groupMin: 22, groupMax: 28, monsters: "Corrupted Ashira hunters", notes: "Putrid Oasis green grove (banner above)." },
  { id: "vz-orcs", zoneId: "vale-of-zintar", name: "Dustrend orc camp", kind: "camp", mx: 26.5, my: 68.0, soloMin: 32, soloMax: 35, groupMin: 26, groupMax: 30, monsters: "Dustrend orcs" },
  { id: "vz-burrowers", zoneId: "vale-of-zintar", name: "Tomb burrowers (termite mounds)", kind: "camp", mx: 30.5, my: 65.5, soloMin: 32, soloMax: 39, groupMin: 32, groupMax: 38, monsters: "Tomb burrowers, devourers" },
  { id: "vz-giants", zoneId: "vale-of-zintar", name: "Sand Giant City", kind: "camp", mx: 55.0, my: 22.0, groupMin: 55, groupMax: 60, monsters: "Sand giants", notes: "Building cluster on the NE plateau (banner above)." },
  { id: "vz-zl-pass", zoneId: "vale-of-zintar", name: "Zoneline: Fallen Pass", kind: "zoneline", mx: 40.0, my: 90.0 },
  { id: "vz-zl-keepers", zoneId: "vale-of-zintar", name: "Zoneline: Keeper's Bight", kind: "zoneline", mx: 78.5, my: 6.0 },
  { id: "vz-zl-flats", zoneId: "vale-of-zintar", name: "Zoneline: Glass Flats", kind: "zoneline", mx: 92.5, my: 22.0 },
  { id: "vz-zl-shoals", zoneId: "vale-of-zintar", name: "Zoneline: Shallow Shoals", kind: "zoneline", mx: 5.0, my: 50.0 },
  { id: "vz-lake", zoneId: "vale-of-zintar", name: "Central lake", kind: "landmark", mx: 34.0, my: 45.0 },
  { id: "vz-pyramid", zoneId: "vale-of-zintar", name: "Wizard pyramid chamber", kind: "dungeon", mx: 35.2, my: 51.5 },
  { id: "vz-fishers", zoneId: "vale-of-zintar", name: "Giant fishing camp (Fisher tents)", kind: "camp", mx: 18.2, my: 32.8, groupMin: 40, groupMax: 50, monsters: "Sand giant fishers", notes: "Nadir the Slaughterer." },
  { id: "vz-beach-giants", zoneId: "vale-of-zintar", name: "Beach giants", kind: "camp", mx: 18.5, my: 41.2, groupMin: 40, groupMax: 50, monsters: "Sand giants", notes: "West shore." },
  { id: "vz-sojourner-lake", zoneId: "vale-of-zintar", name: "Sojourner camp at the lake", kind: "camp", mx: 36.5, my: 46.8, soloMin: 28, soloMax: 36, monsters: "Pyrmos", notes: "Pyrmos / Sojourner camp on the lake shore." },
  { id: "vz-bat-cave", zoneId: "vale-of-zintar", name: "Bat Cave / spider cave", kind: "dungeon", mx: 54.5, my: 49.5, notes: "East of the pyramid." },
  { id: "vz-copper-mine", zoneId: "vale-of-zintar", name: "Copper Mine", kind: "camp", mx: 36.8, my: 55.0, soloMin: 28, soloMax: 36, monsters: "Copperheads, rock vipers", notes: "Cave mouth south of the wizard pyramid." },
  { id: "vz-snake-den", zoneId: "vale-of-zintar", name: "Snake Den", kind: "camp", mx: 53.0, my: 67.0, soloMin: 28, soloMax: 36, monsters: "Snakes", notes: "Cave icon north of the Snake Den banner." },
  { id: "vz-merc-tower", zoneId: "vale-of-zintar", name: "Pyrmos mercenary tower", kind: "camp", mx: 38.8, my: 77.5, groupMin: 30, groupMax: 40, monsters: "Pyrmos mercenaries", notes: "Brown tower icon, south of its label." },

  // Faelindral — Maggot V2 platforms
  { id: "fae-takalea", zoneId: "faelindral", name: "Takalea Scaletender", kind: "quest", mx: 42.0, my: 78.0, notes: "Turn-in: Green Drakeling Scale armor. Lower Tier tannery." },
  { id: "fae-aerin", zoneId: "faelindral", name: "Aerin Mossfang", kind: "quest", mx: 63.5, my: 44.0, notes: "Turn-in: Beastmaster claws and Spirit-Blessed Shawl. Ranger's Rest." },
  { id: "fae-sentinel", zoneId: "faelindral", name: "Sentinel's Terrace", kind: "landmark", mx: 45.0, my: 28.0 },
  { id: "fae-traders", zoneId: "faelindral", name: "Trader's Terrace", kind: "vendor", mx: 52.5, my: 48.0, notes: "Bags, cloth, adventure gear, used weapons/armour." },
  { id: "fae-rangers", zoneId: "faelindral", name: "Ranger's Rest", kind: "trainer", mx: 63.5, my: 44.0 },
  { id: "fae-lower", zoneId: "faelindral", name: "Lower Tier", kind: "vendor", mx: 43.5, my: 85.5, notes: "Grocer, butcher, scrap metal, cook, barkeep." },
  { id: "fae-wall", zoneId: "faelindral", name: "Wall of Green", kind: "landmark", mx: 46.0, my: 50.5 },
  { id: "fae-keepers-lift", zoneId: "faelindral", name: "Keepers Lift", kind: "zoneline", mx: 72.0, my: 31.5, notes: "Out toward Evershade." },
  { id: "fae-balanced", zoneId: "faelindral", name: "The Balanced Branch", kind: "landmark", mx: 65.0, my: 58.5 },
  { id: "fae-vineyard", zoneId: "faelindral", name: "Vineyard Garrison", kind: "landmark", mx: 40.5, my: 30.5 },
  { id: "fae-front-lift", zoneId: "faelindral", name: "Front Lift", kind: "landmark", mx: 22.8, my: 29.5 },
  { id: "fae-observatory", zoneId: "faelindral", name: "Observatory", kind: "landmark", mx: 50.8, my: 26.4, notes: "CLR platform on Maggot V2." },
  { id: "fae-temple-lift", zoneId: "faelindral", name: "Temple Lift", kind: "landmark", mx: 59.0, my: 30.0 },
  { id: "fae-stable-lift", zoneId: "faelindral", name: "Stable Lift", kind: "landmark", mx: 70.5, my: 41.5 },
  { id: "fae-stables", zoneId: "faelindral", name: "Stables", kind: "landmark", mx: 73.5, my: 43.0 },
  { id: "fae-willow", zoneId: "faelindral", name: "Willow's Whisper", kind: "landmark", mx: 54.5, my: 52.0 },
  { id: "fae-binding", zoneId: "faelindral", name: "Binding Tree", kind: "landmark", mx: 43.0, my: 59.0 },
  { id: "fae-lantern", zoneId: "faelindral", name: "Lantern Landing", kind: "trainer", mx: 61.0, my: 63.5, notes: "Maggot ENC platform." },
  { id: "fae-heartwood", zoneId: "faelindral", name: "Heartwood Archive", kind: "landmark", mx: 55.5, my: 69.5 },
  { id: "fae-traveler-lift", zoneId: "faelindral", name: "Traveler's Lift", kind: "landmark", mx: 37.0, my: 68.0 },

  // Evershade Weald — Nindaan
  { id: "ew-lift", zoneId: "evershade-weald", name: "Faelindral lift yards", kind: "camp", mx: 45.8, my: 40.0, soloMin: 1, soloMax: 5, monsters: "Wasps, spiders, drakelings, dryads" },
  { id: "ew-wasps", zoneId: "evershade-weald", name: "Wasp ruins", kind: "camp", mx: 24.0, my: 36.8, soloMin: 3, soloMax: 8, groupMin: 2, groupMax: 6, monsters: "Wasp workers" },
  { id: "ew-orcs", zoneId: "evershade-weald", name: "Fellstone orc scout camp", kind: "camp", mx: 73.8, my: 41.5, soloMin: 3, soloMax: 8, groupMin: 2, groupMax: 6, monsters: "Fellstone orc scouts", notes: "Unintelligible notes turn-in." },
  { id: "ew-wolves", zoneId: "evershade-weald", name: "Hillside wolves", kind: "camp", mx: 16.8, my: 27.5, soloMin: 8, soloMax: 12, groupMin: 6, groupMax: 10, monsters: "Wolves" },
  { id: "ew-zl-glinting", zoneId: "evershade-weald", name: "Zoneline: Glinting Hollow", kind: "zoneline", mx: 16.5, my: 14.0 },
  { id: "ew-zl-keepers", zoneId: "evershade-weald", name: "Zoneline: Keeper's Bight", kind: "zoneline", mx: 40.8, my: 92.0 },
  { id: "ew-zl-blacktide", zoneId: "evershade-weald", name: "Lift to Blacktide Bay", kind: "zoneline", mx: 90.0, my: 92.0 },
  { id: "ew-lookout", zoneId: "evershade-weald", name: "Lookout cave", kind: "landmark", mx: 9.8, my: 22.0 },
  { id: "ew-north-lift", zoneId: "evershade-weald", name: "North lift", kind: "landmark", mx: 26.2, my: 46.8 },
  { id: "ew-to-city", zoneId: "evershade-weald", name: "To Faelindral", kind: "zoneline", mx: 24.8, my: 72.0 },
  { id: "ew-dead-end", zoneId: "evershade-weald", name: "Northeast dead end", kind: "landmark", mx: 93.5, my: 10.8 },
  { id: "ew-spiders", zoneId: "evershade-weald", name: "Spider walkways", kind: "camp", mx: 48.5, my: 20.5, soloMin: 4, soloMax: 9, monsters: "Spiders, black widows" },
  { id: "ew-lift-guardian", zoneId: "evershade-weald", name: "Lift Guardian", kind: "landmark", mx: 21.5, my: 18.5 },
  { id: "ew-dried-bog", zoneId: "evershade-weald", name: "Dried Bog", kind: "camp", mx: 17.0, my: 32.0, soloMin: 3, soloMax: 8, monsters: "Bog fauna" },
  { id: "ew-fungal-lift", zoneId: "evershade-weald", name: "Fungal Lift", kind: "landmark", mx: 25.8, my: 29.5 },
  { id: "ew-skeleton-cave", zoneId: "evershade-weald", name: "Skeleton Cave", kind: "dungeon", mx: 39.5, my: 31.5 },
  { id: "ew-wasp-lift", zoneId: "evershade-weald", name: "Wasp Lift", kind: "landmark", mx: 48.8, my: 32.8 },
  { id: "ew-skeleton-isle", zoneId: "evershade-weald", name: "Skeleton island", kind: "camp", mx: 59.5, my: 50.8, soloMin: 4, soloMax: 10, monsters: "Skeletons" },
  { id: "ew-orcs-south", zoneId: "evershade-weald", name: "South orc camps", kind: "camp", mx: 67.5, my: 66.8, soloMin: 3, soloMax: 8, monsters: "Fellstone orcs" },
  { id: "ew-kernol", zoneId: "evershade-weald", name: "To Kernol Lift", kind: "landmark", mx: 77.2, my: 47.0 },
  { id: "ew-well-cave", zoneId: "evershade-weald", name: "Well Cave", kind: "dungeon", mx: 8.5, my: 57.0 },
  { id: "ew-rest", zoneId: "evershade-weald", name: "Rest", kind: "landmark", mx: 32.2, my: 60.5 },
  { id: "ew-fake-wall", zoneId: "evershade-weald", name: "Fake Cave Wall", kind: "landmark", mx: 82.8, my: 89.5 },
  { id: "ew-dead-sw", zoneId: "evershade-weald", name: "Southwest dead end", kind: "landmark", mx: 8.8, my: 91.0 },

  // Keeper's Bight — wiki schematic
  { id: "kb-wildlife", zoneId: "keepers-bight", name: "Timber wolves & asps", kind: "camp", mx: 72.0, my: 44.5, soloMin: 5, soloMax: 10, monsters: "Timber wolves, bight asps, wasps", notes: "East forest." },
  { id: "kb-poachers", zoneId: "keepers-bight", name: "Poacher camps", kind: "camp", mx: 81.5, my: 25.5, soloMin: 32, soloMax: 38, groupMin: 28, groupMax: 35, monsters: "Poachers (Tolan, Garrus)", notes: "NE camps by the hollow tree." },
  { id: "kb-penshaw", zoneId: "keepers-bight", name: "Penshaw", kind: "landmark", mx: 45.0, my: 37.0, notes: "Town building cluster on the river island, not the label." },
  { id: "kb-docks", zoneId: "keepers-bight", name: "Penshaw docks", kind: "dock", mx: 38.5, my: 34.5 },
  { id: "kb-castle", zoneId: "keepers-bight", name: "River keep", kind: "landmark", mx: 38.0, my: 50.0 },
  { id: "kb-blacktide-dung", zoneId: "keepers-bight", name: "Blacktide Bay dungeon", kind: "dungeon", mx: 54.0, my: 77.0 },
  { id: "kb-blacktide-bay", zoneId: "keepers-bight", name: "Blacktide Bay", kind: "landmark", mx: 36.0, my: 82.0, notes: "South bay water, south of the shoreline label." },
  { id: "kb-zl-evershade", zoneId: "keepers-bight", name: "Zoneline: Evershade Weald", kind: "zoneline", mx: 80.0, my: 6.0 },
  { id: "kb-zl-scarwood", zoneId: "keepers-bight", name: "Zoneline: Scarwood", kind: "zoneline", mx: 97.5, my: 20.8 },
  { id: "kb-zl-shoals", zoneId: "keepers-bight", name: "Zoneline: Shallow Shoals", kind: "zoneline", mx: 4.0, my: 36.5 },
  { id: "kb-zl-vale", zoneId: "keepers-bight", name: "Zoneline: Vale of Zintar", kind: "zoneline", mx: 20.5, my: 95.5 },
  { id: "kb-poachers-south", zoneId: "keepers-bight", name: "South forest poachers", kind: "camp", mx: 86.5, my: 57.0, soloMin: 32, soloMax: 38, monsters: "Poachers" },
  { id: "kb-stables", zoneId: "keepers-bight", name: "Penshaw stables", kind: "vendor", mx: 49.5, my: 29.5, notes: "Horse icon north of town." },
  { id: "kb-north-bridge", zoneId: "keepers-bight", name: "North river bridge", kind: "landmark", mx: 48.0, my: 23.5 },
  { id: "kb-farms", zoneId: "keepers-bight", name: "South island farms", kind: "landmark", mx: 40.5, my: 58.5 },
  { id: "kb-hollow-ne", zoneId: "keepers-bight", name: "Northeast hollow tree", kind: "landmark", mx: 81.5, my: 29.5 },
  { id: "kb-hollow-se", zoneId: "keepers-bight", name: "Southeast hollow tree", kind: "landmark", mx: 81.5, my: 59.0 },
  { id: "kb-poachers-north", zoneId: "keepers-bight", name: "North river poachers", kind: "camp", mx: 59.5, my: 14.5, soloMin: 32, soloMax: 38, monsters: "Poachers", notes: "Camps north of Penshaw." },

  // Scarwood
  { id: "sw-bandits", zoneId: "scarwood", name: "River island bandits", kind: "camp", mx: 47.5, my: 42.2, soloMin: 27, soloMax: 32, groupMin: 22, groupMax: 27, monsters: "Bandits", notes: "Bridge / island camp on the river." },
  { id: "sw-sunken", zoneId: "scarwood", name: "Sunken Resort", kind: "dungeon", mx: 39.6, my: 75.8, notes: "Archway icon in the lake, not the label." },
  { id: "sw-zl-keepers", zoneId: "scarwood", name: "Zoneline: Keeper's Bight", kind: "zoneline", mx: 2.5, my: 47.5 },
  { id: "sw-zl-lost", zoneId: "scarwood", name: "Fields of the Lost", kind: "zoneline", mx: 97.5, my: 22.6 },
  { id: "sw-cabins", zoneId: "scarwood", name: "Southwest cabins", kind: "landmark", mx: 9.2, my: 73.6 },
  { id: "sw-ruins", zoneId: "scarwood", name: "North ruins", kind: "camp", mx: 63.0, my: 27.6, soloMin: 28, soloMax: 34, monsters: "Undead, bandits" },
  { id: "sw-falls", zoneId: "scarwood", name: "North waterfall", kind: "landmark", mx: 48.4, my: 24.4 },
  { id: "sw-se-cave", zoneId: "scarwood", name: "Southeast cave", kind: "dungeon", mx: 91.4, my: 80.1 },
  { id: "sw-nw-cabin", zoneId: "scarwood", name: "Northwest cabin", kind: "landmark", mx: 14.6, my: 11.4 },
  { id: "sw-north-camp", zoneId: "scarwood", name: "North hillside camp", kind: "camp", mx: 47.0, my: 18.8, soloMin: 24, soloMax: 32, monsters: "Bandits / undead" },
  { id: "sw-lake", zoneId: "scarwood", name: "West lake", kind: "landmark", mx: 31.5, my: 62.5 },

  { id: "te-ashira", zoneId: "tel-ekir", name: "Ashira entrance", kind: "camp", mx: 22.0, my: 61.5, groupMin: 9, groupMax: 16, monsters: "Ashira", notes: "West cave mouth. Four named. Alpha camp higher." },
  { id: "te-bloodynose", zoneId: "tel-ekir", name: "Grand Overlord Bloodynose", kind: "named", mx: 78.0, my: 27.0, soloMin: 17, soloMax: 22, groupMin: 10, groupMax: 15, monsters: "Bloodynose goblins" },
  { id: "te-life-font", zoneId: "tel-ekir", name: "Guardian of the Life Font", kind: "landmark", mx: 44.5, my: 28.5 },
  { id: "te-hashamaran", zoneId: "tel-ekir", name: "Hashamaran, First Among Alphas", kind: "named", mx: 22.0, my: 69.0, notes: "Ashira west caves. Map #12." },
  { id: "te-hag", zoneId: "tel-ekir", name: "Bloodynose hag", kind: "named", mx: 74.0, my: 36.0, notes: "Bloodynose temple, map #2." },
  { id: "te-raiser", zoneId: "tel-ekir", name: "Bloodynose raiser", kind: "named", mx: 77.0, my: 40.0, notes: "Bloodynose temple, map #3." },
  { id: "te-annalist", zoneId: "tel-ekir", name: "Bloodynose annalist", kind: "named", mx: 72.5, my: 42.5, notes: "Bloodynose temple, map #4." },
  { id: "te-anguished", zoneId: "tel-ekir", name: "Anguished spirit", kind: "named", mx: 17.5, my: 61.5, notes: "Ashira caves, map #1." },
  { id: "te-fortune", zoneId: "tel-ekir", name: "Ashira fortune teller", kind: "named", mx: 21.0, my: 56.0, notes: "Map #2." },
  { id: "te-alchemist", zoneId: "tel-ekir", name: "Ashira alchemist", kind: "named", mx: 25.0, my: 71.5, notes: "Map #3." },
  { id: "te-waterfall", zoneId: "tel-ekir", name: "Life Font waterfall", kind: "landmark", mx: 44.0, my: 38.5 },
  { id: "te-zl-sungreet", zoneId: "tel-ekir", name: "Zoneline: Sungreet Strand", kind: "zoneline", mx: 86.5, my: 17.5 },
  { id: "te-zl-dunes", zoneId: "tel-ekir", name: "Zoneline: Shaded Dunes", kind: "zoneline", mx: 59.5, my: 78.5 },
  { id: "te-goblin-caves", zoneId: "tel-ekir", name: "Bloodynose caves", kind: "camp", mx: 69.5, my: 36.5, soloMin: 17, soloMax: 22, monsters: "Bloodynose goblins" },

  { id: "tw-entrance", zoneId: "tomb-wyrmsbane", name: "Entrance undead", kind: "camp", mx: 52, my: 78, soloMin: 8, soloMax: 14, groupMin: 4, groupMax: 14, monsters: "Undead", notes: "By To Night Harbor." },
  { id: "tw-zl-harbor", zoneId: "tomb-wyrmsbane", name: "Zoneline: Night Harbor", kind: "zoneline", mx: 52, my: 88 },
  { id: "tw-zl-ancient", zoneId: "tomb-wyrmsbane", name: "Zoneline: Ancient Crypt", kind: "zoneline", mx: 42, my: 78 },
  { id: "tw-cloth", zoneId: "tomb-wyrmsbane", name: "1–3F Plate & Cloth", kind: "landmark", mx: 52, my: 32 },
  { id: "tw-chain-w", zoneId: "tomb-wyrmsbane", name: "3–4F Chain (west)", kind: "landmark", mx: 22, my: 32 },
  { id: "tw-plate", zoneId: "tomb-wyrmsbane", name: "5–6F Plate & Leather", kind: "landmark", mx: 78, my: 18 },
  { id: "tw-chain-e", zoneId: "tomb-wyrmsbane", name: "3–4F Chain (east)", kind: "landmark", mx: 78, my: 62 },
  { id: "tw-quartermaster", zoneId: "tomb-wyrmsbane", name: "Quartermaster Boothroy", kind: "quest", mx: 52, my: 78, notes: "Map #1, south-center of 1–3F." },
  { id: "tw-jakob", zoneId: "tomb-wyrmsbane", name: "Jakob (Cloth)", kind: "named", mx: 64, my: 62, notes: "Map #2." },
  { id: "tw-timmon", zoneId: "tomb-wyrmsbane", name: "Timmon (Cloth)", kind: "named", mx: 38, my: 48, notes: "Map #3." },
  { id: "tw-construct", zoneId: "tomb-wyrmsbane", name: "Bone Construct", kind: "named", mx: 54, my: 22, notes: "Map #4, north 1–3F." },
  { id: "tw-grogan", zoneId: "tomb-wyrmsbane", name: "Lt. Grogan (Plate)", kind: "named", mx: 62, my: 32, notes: "Map #5." },
  { id: "tw-dario", zoneId: "tomb-wyrmsbane", name: "Dario (Chain)", kind: "named", mx: 76, my: 74, notes: "Map #6, SE chain floor." },
  { id: "tw-artificer", zoneId: "tomb-wyrmsbane", name: "Artificer", kind: "named", mx: 88, my: 78, notes: "Map #7." },
  { id: "tw-gildas", zoneId: "tomb-wyrmsbane", name: "Grandmaster Gildas (Leather)", kind: "named", mx: 86, my: 22, notes: "Map #8, 5–6F." },
  { id: "tw-obadiah", zoneId: "tomb-wyrmsbane", name: "Grandmaster Obadiah (Leather)", kind: "named", mx: 86, my: 52, notes: "Map #9." },
  { id: "tw-haines", zoneId: "tomb-wyrmsbane", name: "High Marshal Haines (Plate)", kind: "named", mx: 78, my: 36, notes: "Map #10." },
  { id: "tw-gerhard", zoneId: "tomb-wyrmsbane", name: "Gerhard Graves (Chain)", kind: "named", mx: 12, my: 42, notes: "Map #11, west 3–4F." },
  { id: "tw-connect-a", zoneId: "tomb-wyrmsbane", name: "Floor connection A", kind: "landmark", mx: 36, my: 80, notes: "Map A — pit/connection between floors." },
  { id: "tw-pit-w", zoneId: "tomb-wyrmsbane", name: "Pit trap (west)", kind: "landmark", mx: 24, my: 42, notes: "Red X on Walabus map." },

  { id: "shoals-pirates", zoneId: "shallow-shoals", name: "Island 1 — pirates / cultists", kind: "camp", mx: 16, my: 86, groupMin: 40, groupMax: 50, monsters: "Pirates, cultists, fire giants" },
  { id: "shoals-researchers", zoneId: "shallow-shoals", name: "Island 3 — researchers", kind: "landmark", mx: 14, my: 72 },
  { id: "shoals-ashira", zoneId: "shallow-shoals", name: "Island 4 — Banished Ashira", kind: "camp", mx: 18, my: 68, groupMin: 20, groupMax: 28, monsters: "Ashira" },
  { id: "shoals-player", zoneId: "shallow-shoals", name: "Island 5 — player island", kind: "landmark", mx: 28, my: 64 },
  { id: "shoals-giants", zoneId: "shallow-shoals", name: "Island 6 — sand giants", kind: "camp", mx: 36, my: 58, groupMin: 50, groupMax: 60, monsters: "Sand giants" },
  { id: "shoals-spectre", zoneId: "shallow-shoals", name: "Island 7 — Spectre Island", kind: "camp", mx: 16, my: 60, monsters: "Spectres" },
  { id: "shoals-zaedin", zoneId: "shallow-shoals", name: "Island 8 — Zaedin's Landing", kind: "landmark", mx: 16, my: 50, notes: "Boat stop. Bahaara / Syndicate / Elementals." },
  { id: "shoals-basilisks", zoneId: "shallow-shoals", name: "Island 9 — basilisks", kind: "camp", mx: 8, my: 50, soloMin: 38, soloMax: 44, groupMin: 30, groupMax: 35, monsters: "Basilisks", notes: "West of Zaedin's Landing." },
  { id: "shoals-villagers", zoneId: "shallow-shoals", name: "Island 13 — villagers / goblins", kind: "camp", mx: 26, my: 32, monsters: "Villagers, goblins" },
  { id: "shoals-orcs", zoneId: "shallow-shoals", name: "Island 17 — orc fort", kind: "camp", mx: 18, my: 20, groupMin: 40, groupMax: 50, monsters: "Orcs" },
  { id: "shoals-10", zoneId: "shallow-shoals", name: "Island 10", kind: "landmark", mx: 22, my: 52, notes: "Map: nothing?" },
  { id: "shoals-giants-11", zoneId: "shallow-shoals", name: "Island 11 — sand giants", kind: "camp", mx: 38, my: 48, groupMin: 50, groupMax: 60, monsters: "Sand giants", notes: "Links to 6 by a shallow road." },
  { id: "shoals-giants-12", zoneId: "shallow-shoals", name: "Island 12 — sand giants", kind: "camp", mx: 32, my: 42, groupMin: 50, groupMax: 60, monsters: "Sand giants", notes: "Links to 11." },
  { id: "shoals-pirates-14", zoneId: "shallow-shoals", name: "Island 14 — castaway pirates", kind: "camp", mx: 10, my: 38, groupMin: 40, groupMax: 50, monsters: "Pirates" },
  { id: "shoals-fishers-15", zoneId: "shallow-shoals", name: "Island 15 — Bahaara fishers", kind: "camp", mx: 10, my: 28, monsters: "Bahaara fishers" },
  { id: "shoals-fishers-16", zoneId: "shallow-shoals", name: "Island 16 — Bahaara / elementals", kind: "camp", mx: 10, my: 24, monsters: "Bahaara fishers, elementals" },
  { id: "shoals-orcs-18", zoneId: "shallow-shoals", name: "Island 18 — orcs / dark elves", kind: "camp", mx: 10, my: 12, groupMin: 40, groupMax: 50, monsters: "Orcs, dark elves" },
  { id: "shoals-ruins-19", zoneId: "shallow-shoals", name: "Island 19 — underwater ruins", kind: "dungeon", mx: 32, my: 28, notes: "Underwater ruins / sharks." },
  { id: "shoals-island-2", zoneId: "shallow-shoals", name: "Island 2", kind: "landmark", mx: 18, my: 78, notes: "Map: nothing?" },

  { id: "ud-yards", zoneId: "underdocks", name: "Underdock yards", kind: "camp", mx: 48, my: 48, soloMin: 1, soloMax: 8, monsters: "Rats, bats, dock vermin" },
  { id: "ud-bridge", zoneId: "underdocks", name: "Wall Bridge", kind: "landmark", mx: 50, my: 30 },
  { id: "ud-shrooms-nw", zoneId: "underdocks", name: "Northwest shrooms", kind: "camp", mx: 38, my: 16, soloMin: 1, soloMax: 8, monsters: "Mushrooms / dock vermin" },
  { id: "ud-shrooms-ne", zoneId: "underdocks", name: "Northeast shrooms", kind: "camp", mx: 72, my: 16, soloMin: 1, soloMax: 8, monsters: "Mushrooms / dock vermin" },
  { id: "ud-alchemist", zoneId: "underdocks", name: "Alchemist", kind: "vendor", mx: 30, my: 34 },
  { id: "ud-garden", zoneId: "underdocks", name: "High-up garden", kind: "landmark", mx: 12, my: 36 },
  { id: "ud-meditation", zoneId: "underdocks", name: "Meditation room", kind: "landmark", mx: 24, my: 34, notes: "By newbie spawn." },
  { id: "ud-horsetamer", zoneId: "underdocks", name: "Horsetamer", kind: "vendor", mx: 26, my: 36 },
  { id: "ud-disenchanter", zoneId: "underdocks", name: "Disenchanter", kind: "vendor", mx: 32, my: 50 },
  { id: "ud-cooks", zoneId: "underdocks", name: "Cooks", kind: "vendor", mx: 62, my: 38 },
  { id: "ud-tannery", zoneId: "underdocks", name: "Tannery / leather", kind: "vendor", mx: 64, my: 42 },
  { id: "ud-bowyer", zoneId: "underdocks", name: "Bowyer", kind: "vendor", mx: 66, my: 44 },
  { id: "ud-blacksmith", zoneId: "underdocks", name: "Blacksmith (3rd floor)", kind: "vendor", mx: 50, my: 44 },
  { id: "ud-bar", zoneId: "underdocks", name: "Bar", kind: "vendor", mx: 78, my: 36 },
  { id: "ud-music", zoneId: "underdocks", name: "Music guildmasters", kind: "trainer", mx: 86, my: 28, notes: "Wiz / Enc / Ele / Ench." },
  { id: "ud-physical", zoneId: "underdocks", name: "Physical guildmasters", kind: "trainer", mx: 86, my: 34 },
  { id: "ud-archer", zoneId: "underdocks", name: "Archer / Ranger (2nd floor)", kind: "trainer", mx: 86, my: 40 },
  { id: "ud-cleric", zoneId: "underdocks", name: "Cleric (2nd floor)", kind: "trainer", mx: 86, my: 46 },
  { id: "ud-bank-2", zoneId: "underdocks", name: "Bank (2nd floor)", kind: "vendor", mx: 82, my: 58 },
  { id: "ud-lumberjack", zoneId: "underdocks", name: "Lumberjack", kind: "vendor", mx: 72, my: 62 },
  { id: "ud-merchant", zoneId: "underdocks", name: "Merchant (up high)", kind: "vendor", mx: 62, my: 66 },
  { id: "ud-dockworkers", zoneId: "underdocks", name: "Dockworkers", kind: "camp", mx: 50, my: 60, soloMin: 1, soloMax: 8, monsters: "Dockworkers" },
  { id: "ud-church", zoneId: "underdocks", name: "Evil church", kind: "landmark", mx: 48, my: 86 },
  { id: "ud-waterfall", zoneId: "underdocks", name: "Spooky waterfall", kind: "landmark", mx: 82, my: 78 },
  { id: "ud-vines", zoneId: "underdocks", name: "Vines", kind: "landmark", mx: 32, my: 68 },
  { id: "ud-spawn", zoneId: "underdocks", name: "Newbie spawn", kind: "landmark", mx: 22, my: 28 },
  { id: "ud-bank", zoneId: "underdocks", name: "Bank", kind: "vendor", mx: 28, my: 38 },
  { id: "ud-tele", zoneId: "underdocks", name: "Teleporter", kind: "zoneline", mx: 18, my: 42 },
  { id: "ud-ranger", zoneId: "underdocks", name: "Ranger guildmaster", kind: "trainer", mx: 12, my: 38 },
  { id: "ud-druid", zoneId: "underdocks", name: "Druid guildmaster", kind: "trainer", mx: 18, my: 72 },
  { id: "ud-shaman", zoneId: "underdocks", name: "Shaman guildmaster", kind: "trainer", mx: 28, my: 78 },
  { id: "ud-necro", zoneId: "underdocks", name: "Necro / SK guildmasters", kind: "trainer", mx: 58, my: 88 },
  { id: "ud-graveyard", zoneId: "underdocks", name: "Graveyard", kind: "camp", mx: 72, my: 82, soloMin: 8, soloMax: 14, monsters: "Undead" },
  { id: "ud-casters", zoneId: "underdocks", name: "Caster guildmasters", kind: "trainer", mx: 78, my: 30, notes: "Music, wiz/enc, ele, ench." },
  { id: "ud-fighter", zoneId: "underdocks", name: "Fighter guildmaster", kind: "trainer", mx: 78, my: 48 },
  { id: "ud-boat", zoneId: "underdocks", name: "Boat", kind: "dock", mx: 50, my: 12 },
  { id: "ud-zl-irem", zoneId: "underdocks", name: "Zoneline: Caves of Irem", kind: "zoneline", mx: 50, my: 6, notes: "River north out of the docks into the caves, then the Great Cavern Sea and Ail'vorith." },
  { id: "av-toilmaster", zoneId: "ail-vorith", name: "Toilmaster Vorith", kind: "quest", mx: 34.1, my: 17.9, notes: "Deep Elf starter. Where you were standing in the client." },
  { id: "av-foreign", zoneId: "ail-vorith", name: "Foreign Quarter", kind: "landmark", mx: 32.9, my: 23.0, notes: "Just south of the toilmaster." },
  { id: "av-foreign-east", zoneId: "ail-vorith", name: "Foreign Quarter", kind: "landmark", mx: 75.7, my: 27.3, notes: "East quarter marker in the client scene." },
  { id: "av-gate-double", zoneId: "ail-vorith", name: "Double gate", kind: "landmark", mx: 57.3, my: 17.8, notes: "North gate on the city plate." },
  { id: "av-gate", zoneId: "ail-vorith", name: "Gate", kind: "landmark", mx: 56.6, my: 41.5, notes: "Gate south of the palace." },
  { id: "av-bank", zoneId: "ail-vorith", name: "Bank", kind: "vendor", mx: 22.3, my: 42.7 },
  { id: "av-bank-ith", zoneId: "ail-vorith", name: "Bank (Ith'vayen)", kind: "vendor", mx: 64.2, my: 71.0, notes: "House bank on the guild row." },
  { id: "av-harbor", zoneId: "ail-vorith", name: "Vaelxirith harbor", kind: "landmark", mx: 15.8, my: 67.6 },
  { id: "av-harbor-inner", zoneId: "ail-vorith", name: "Inner harbor", kind: "landmark", mx: 17.4, my: 77.2, notes: "Second harbor mouth, south of the main dock." },
  { id: "av-zl-sea", zoneId: "ail-vorith", name: "Zoneline: Night Harbor", kind: "zoneline", mx: 55.5, my: 31.1, notes: "Palace boat. Hull center of the boat out to Night Harbor." },
  { id: "av-palace", zoneId: "ail-vorith", name: "Queen's palace", kind: "landmark", mx: 60.1, my: 29.2, notes: "Palace mesh north of the guild row, beside the boat." },
  { id: "av-xal", zoneId: "ail-vorith", name: "Xal'tharn guild hall", kind: "trainer", mx: 58.0, my: 74.6 },
  { id: "av-wizard", zoneId: "ail-vorith", name: "Wizard guild (Hal'kareth)", kind: "trainer", mx: 62.3, my: 72.1 },
  { id: "av-necro", zoneId: "ail-vorith", name: "Necro / Elementalist (Varros)", kind: "trainer", mx: 70.0, my: 67.7 },
  { id: "av-paladin", zoneId: "ail-vorith", name: "Paladin / Cleric guild (Drezzorith)", kind: "trainer", mx: 72.2, my: 66.3, notes: "Your house." },
  { id: "av-foreign-quarter-0", zoneId: "ail-vorith", name: "Foreign Quarter", kind: "landmark", mx: 27.7, my: 37.1 },
  { id: "av-shop-varros-1", zoneId: "ail-vorith", name: "Shop (Varros)", kind: "vendor", mx: 74.5, my: 65.1 },
  { id: "av-club-varros-2", zoneId: "ail-vorith", name: "Club (Varros)", kind: "vendor", mx: 77.1, my: 63.6 },
  { id: "av-bowyer-vael-xirith-3", zoneId: "ail-vorith", name: "Bowyer (Vael'xirith)", kind: "vendor", mx: 75.8, my: 64.3 },
  { id: "av-guard-house-xal-tharn-4", zoneId: "ail-vorith", name: "Guard House (Xal'tharn)", kind: "landmark", mx: 78.0, my: 63.0 },
  { id: "av-alchemy-trainers-hal-kareth-5", zoneId: "ail-vorith", name: "Alchemy Trainers (Hal'kareth)", kind: "trainer", mx: 78.5, my: 62.8 },
  { id: "av-council-chambers-xal-tharn-6", zoneId: "ail-vorith", name: "Council Chambers (Xal'tharn)", kind: "landmark", mx: 84.2, my: 59.4 },
  { id: "av-to-harbor-ith-vayen-7", zoneId: "ail-vorith", name: "To Harbor (Ith'vayen)", kind: "landmark", mx: 65.8, my: 70.1 },
  { id: "av-to-clr-pal-guild-8", zoneId: "ail-vorith", name: "To CLR/PAL Guild", kind: "landmark", mx: 80.0, my: 61.9 },
  { id: "av-wine-spirits-varros-9", zoneId: "ail-vorith", name: "Wine/Spirits (Varros)", kind: "vendor", mx: 80.8, my: 61.4 },
  { id: "av-inn-ith-vayen-10", zoneId: "ail-vorith", name: "Inn (Ith'vayen)", kind: "vendor", mx: 63.4, my: 71.4 },
  { id: "av-temple-drezzorith-11", zoneId: "ail-vorith", name: "Temple (Drezzorith)", kind: "landmark", mx: 73.3, my: 65.7 },
  { id: "av-library-drezzorith-12", zoneId: "ail-vorith", name: "Library (Drezzorith)", kind: "landmark", mx: 75.2, my: 64.7 },
  { id: "av-inn-cells-varros-13", zoneId: "ail-vorith", name: "Inn/Cells (Varros)", kind: "vendor", mx: 77.8, my: 63.2 },
  { id: "av-council-chambers-xal-tharn-14", zoneId: "ail-vorith", name: "Council Chambers (Xal'tharn)", kind: "landmark", mx: 83.1, my: 60.1 },
  { id: "av-temple-drezzorith-15", zoneId: "ail-vorith", name: "Temple (Drezzorith)", kind: "landmark", mx: 69.5, my: 67.9 },
  { id: "av-temple-library-drezzorith-16", zoneId: "ail-vorith", name: "Temple/Library (Drezzorith)", kind: "landmark", mx: 68.4, my: 68.6 },
  { id: "av-martyrs-vael-xirith-17", zoneId: "ail-vorith", name: "Martyrs (Vael'xirith)", kind: "landmark", mx: 72.6, my: 66.1 },
  { id: "av-shrine-ith-vayen-18", zoneId: "ail-vorith", name: "Shrine (Ith'vayen)", kind: "landmark", mx: 72.8, my: 66.0 },
  { id: "av-tavern-vael-xirith-19", zoneId: "ail-vorith", name: "Tavern (Vael'xirith)", kind: "vendor", mx: 72.4, my: 66.3 },
  { id: "av-potion-seller-hal-kareth-20", zoneId: "ail-vorith", name: "Potion seller (Hal'kareth)", kind: "vendor", mx: 60.0, my: 73.4 },
  { id: "av-open-market-varros-21", zoneId: "ail-vorith", name: "Open Market (Varros)", kind: "vendor", mx: 76.7, my: 63.8 },
  { id: "av-plate-chain-shop-vael-xirith-22", zoneId: "ail-vorith", name: "Plate/Chain Shop (Vael'xirith)", kind: "vendor", mx: 71.1, my: 67.0 },
  { id: "av-leather-ith-vayen-23", zoneId: "ail-vorith", name: "Leather (Ith'vayen)", kind: "vendor", mx: 69.8, my: 67.7 },
  { id: "av-to-harbor-commons-24", zoneId: "ail-vorith", name: "To Harbor (Commons)", kind: "landmark", mx: 63.2, my: 71.6 },
  { id: "av-tavern-varros-25", zoneId: "ail-vorith", name: "Tavern (Varros)", kind: "vendor", mx: 80.4, my: 61.6 },
  { id: "av-jewel-tailor-ith-vayen-26", zoneId: "ail-vorith", name: "Jewel+Tailor (Ith'vayen)", kind: "vendor", mx: 67.8, my: 68.9 },
  { id: "av-temple-xal-tharn-27", zoneId: "ail-vorith", name: "Temple (Xal'tharn)", kind: "landmark", mx: 82.8, my: 60.2 },
  { id: "av-library-hal-kareth-28", zoneId: "ail-vorith", name: "Library (Hal'kareth)", kind: "landmark", mx: 63.6, my: 71.4 },
  { id: "av-pilgrim-s-inn-drezzorith-29", zoneId: "ail-vorith", name: "Pilgrim's Inn (Drezzorith)", kind: "vendor", mx: 68.2, my: 68.7 },
  { id: "av-palace-stairs-30", zoneId: "ail-vorith", name: "Palace stairs", kind: "landmark", mx: 56.4, my: 31.3 },
  { id: "av-boat-31", zoneId: "ail-vorith", name: "Moored boat", kind: "landmark", mx: 57.9, my: 34.2 },
  { id: "av-gate-32", zoneId: "ail-vorith", name: "Gate", kind: "landmark", mx: 61.0, my: 39.1 },
  { id: "av-boat-33", zoneId: "ail-vorith", name: "Moored boat", kind: "landmark", mx: 51.0, my: 30.9 },
  { id: "gcs-zl-irem", zoneId: "great-cavern-sea", name: "Zoneline: Caves of Irem", kind: "zoneline", mx: 50, my: 94 },
  { id: "gcs-zl-ail", zoneId: "great-cavern-sea", name: "Zoneline: Ail'vorith", kind: "zoneline", mx: 94, my: 42, notes: "Boat to the Deep Elf city." },
  { id: "gcs-zl-docks", zoneId: "great-cavern-sea", name: "Zoneline: Underdocks", kind: "zoneline", mx: 28, my: 18 },
  { id: "gcs-zl-rothold", zoneId: "great-cavern-sea", name: "Zoneline: Rothold", kind: "zoneline", mx: 6, my: 62 },
  { id: "rh-zl-sea", zoneId: "rothold", name: "Zoneline: Great Cavern Sea", kind: "zoneline", mx: 94, my: 50 },
  { id: "bm-zl-ail", zoneId: "blind-midden", name: "Zoneline: Ail'vorith", kind: "zoneline", mx: 6, my: 50 },

  { id: "ac-harseal", zoneId: "ancient-crypt", name: "Researcher Harseal", kind: "quest", mx: 58, my: 12, notes: "Map #1, north." },
  { id: "ac-gallier", zoneId: "ancient-crypt", name: "Librarian Gallier", kind: "quest", mx: 42, my: 32, notes: "Map #2." },
  { id: "ac-brahson", zoneId: "ancient-crypt", name: "Brahson the Butcher", kind: "named", mx: 42, my: 62, notes: "Map #3." },
  { id: "ac-mangles", zoneId: "ancient-crypt", name: "Commander Mangles", kind: "named", mx: 38, my: 78, notes: "Map #4." },
  { id: "ac-illya", zoneId: "ancient-crypt", name: "Skyseer Illya", kind: "named", mx: 22, my: 72, notes: "Map #5, SW room." },
  { id: "ac-zl-wyrm", zoneId: "ancient-crypt", name: "Zoneline: Wyrmsbane Tomb", kind: "zoneline", mx: 62, my: 10 },
  { id: "ac-zl-dunes", zoneId: "ancient-crypt", name: "Zoneline: Shaded Dunes", kind: "zoneline", mx: 72, my: 62 },
  { id: "ac-pit-irem", zoneId: "ancient-crypt", name: "Pit to Caves of Irem", kind: "dungeon", mx: 38, my: 48, notes: "Map D." },
  { id: "ac-false-floor", zoneId: "ancient-crypt", name: "False floor pit trap", kind: "landmark", mx: 52, my: 22, notes: "Map A, south of #1." },
  { id: "ac-ladder", zoneId: "ancient-crypt", name: "Ladder", kind: "landmark", mx: 52, my: 32, notes: "Map B." },
  { id: "ac-ladder-out", zoneId: "ancient-crypt", name: "Ladder out of pit", kind: "landmark", mx: 46, my: 28, notes: "Map C." },

  { id: "ic-brood", zoneId: "infested-crypt", name: "Crypt Broodmother", kind: "named", mx: 52, my: 22, notes: "Map #1, north room." },
  { id: "ic-ladder", zoneId: "infested-crypt", name: "Spiderweb ladder", kind: "landmark", mx: 58, my: 48, notes: "Map A." },
  { id: "ic-zl-dunes", zoneId: "infested-crypt", name: "Zoneline: Shaded Dunes", kind: "zoneline", mx: 32, my: 78 },

  { id: "gc-rats", zoneId: "grain-cellar", name: "Sneaky rats", kind: "camp", mx: 32, my: 58, soloMin: 22, soloMax: 28, monsters: "Rats", notes: "Map #1." },
  { id: "gc-zakariah", zoneId: "grain-cellar", name: "Zakariah Shriki", kind: "named", mx: 48, my: 38, notes: "Map #2." },
  { id: "gc-rais", zoneId: "grain-cellar", name: "Rais Muzari", kind: "named", mx: 28, my: 38, notes: "Map #3." },
  { id: "gc-leila", zoneId: "grain-cellar", name: "Leila al-Bahri", kind: "named", mx: 62, my: 52, notes: "Map #4, stair landing with Khalid and Fariha." },
  { id: "gc-khalid", zoneId: "grain-cellar", name: "Khalid al-Bahri", kind: "named", mx: 64, my: 54, notes: "Map #4." },
  { id: "gc-fariha", zoneId: "grain-cellar", name: "Fariha bint Nizar", kind: "named", mx: 60, my: 56, notes: "Map #4." },
  { id: "fw-entrance", zoneId: "fallen-watch", name: "Fallen Watch interior", kind: "landmark", mx: 50, my: 50, notes: "Entered from the fort on Fallen Pass." },

  { id: "irem-mushrooms", zoneId: "caves-of-irem", name: "Mushroom cavern", kind: "camp", mx: 38, my: 48, soloMin: 8, soloMax: 18, monsters: "Insects, cave fauna" },
  { id: "irem-grove", zoneId: "caves-of-irem", name: "Green grove", kind: "landmark", mx: 78, my: 28 },
  { id: "irem-zl-sea", zoneId: "caves-of-irem", name: "Zoneline: Great Cavern Sea", kind: "zoneline", mx: 62, my: 8 },
  { id: "irem-zl-docks", zoneId: "caves-of-irem", name: "Zoneline: Underdocks", kind: "zoneline", mx: 52, my: 92 },
  { id: "irem-cyan-shrooms", zoneId: "caves-of-irem", name: "Cyan mushroom field", kind: "camp", mx: 32, my: 32, soloMin: 8, soloMax: 16, monsters: "Insects, cave fauna" },
  { id: "irem-red-shrooms", zoneId: "caves-of-irem", name: "Red mushroom field", kind: "camp", mx: 42, my: 58, soloMin: 10, soloMax: 18, monsters: "Beetles, cave fauna" },
  { id: "irem-ship", zoneId: "caves-of-irem", name: "River wreck", kind: "landmark", mx: 58, my: 44 },
  { id: "irem-pyramid", zoneId: "caves-of-irem", name: "North pyramid", kind: "landmark", mx: 52, my: 10 },
  { id: "irem-grey-x", zoneId: "caves-of-irem", name: "Grey chamber mark", kind: "named", mx: 86, my: 52, notes: "Red X in the east grey room." },
  { id: "irem-west-npc", zoneId: "caves-of-irem", name: "West cavern NPC", kind: "quest", mx: 14, my: 52 },

  { id: "gt-entrance", zoneId: "grimtide-sanctum", name: "Sanctum entrance", kind: "landmark", mx: 8, my: 52 },
  { id: "gt-hall", zoneId: "grimtide-sanctum", name: "Central hall", kind: "camp", mx: 48, my: 48, groupMin: 15, groupMax: 25, monsters: "Undead, cultists" },
  { id: "gt-pool", zoneId: "grimtide-sanctum", name: "Sunken pool", kind: "landmark", mx: 62, my: 68 },
  { id: "gt-west-door", zoneId: "grimtide-sanctum", name: "West door", kind: "landmark", mx: 8, my: 48 },
  { id: "gt-north-loops", zoneId: "grimtide-sanctum", name: "North cave loops", kind: "camp", mx: 32, my: 18, groupMin: 15, groupMax: 25, monsters: "Undead, cultists" },
  { id: "gt-east-stair", zoneId: "grimtide-sanctum", name: "East stair hall", kind: "landmark", mx: 82, my: 48 },

  { id: "bt-zl-evershade", zoneId: "blacktide-bay", name: "Elevator to Evershade", kind: "zoneline", mx: 48, my: 8 },
  { id: "bt-zl-keepers", zoneId: "blacktide-bay", name: "Elevator to Keeper's Bight", kind: "zoneline", mx: 72, my: 88 },
  { id: "bt-ships", zoneId: "blacktide-bay", name: "Anchored ships", kind: "dock", mx: 28, my: 88 },
  { id: "bt-entrance", zoneId: "blacktide-bay", name: "Bay entrance", kind: "landmark", mx: 70, my: 72 },
];
