/** Seed atlas for Aêthoril — Early Access zones and community hunting camps. */

const regions = [
  {
    id: "szuur",
    name: "Szuur",
    blurb: "Desert and coast of western Aêthoril. Night Harbor is the jewel of the west.",
  },
  {
    id: "calafrey",
    name: "Calafrey",
    blurb: "Enchanted green lands of the Elves, north of the dunes.",
  },
  {
    id: "deep",
    name: "The Deep",
    blurb: "The underworld beneath Aêthoril — as vast as the surface above.",
  },
];

const zones = [
  {
    id: "night-harbor",
    name: "Night Harbor",
    regionId: "szuur",
    kind: "city",
    layer: "surface",
    start: true,
    levelMin: 1,
    levelMax: 20,
    adjacent: ["shaded-dunes", "sungreet-strand", "tomb-wyrmsbane", "night-harbor-sewers", "underdocks"],
    description:
      "Crown jewel of the west. Massive port city and starting hub for good and many neutral folk. No in-game map — learn the gates, market, and docks by walking them.",
    path: "M 168 508 L 248 478 L 338 492 L 368 548 L 338 628 L 248 648 L 168 612 L 148 552 Z",
    labelX: 248,
    labelY: 555,
    camps: [
      {
        id: "nh-starting-yards",
        name: "North & West gate yards",
        soloMin: 1,
        soloMax: 5,
        groupMin: 1,
        groupMax: 5,
        monsters: "Rats, bats, snakes, spiders, beetles, skeletons, Ashira",
        notes: "Classic newbie yards. North and west gates.",
        x: 210,
        y: 500,
      },
      {
        id: "nh-shaded-bloom",
        name: "Shaded Bloom Inn basement",
        soloMin: 1,
        soloMax: 3,
        groupMin: 1,
        groupMax: 3,
        monsters: "Beetles, rats",
        notes: "Indoor starter grind.",
        x: 250,
        y: 560,
      },
      {
        id: "nh-saltbreeze",
        name: "Saltbreeze Park",
        soloMin: 1,
        soloMax: 5,
        groupMin: 1,
        groupMax: 5,
        monsters: "Bats",
        notes: "Bats spawn at night.",
        x: 230,
        y: 590,
      },
      {
        id: "nh-necropolis",
        name: "Necropolis front yard",
        soloMin: 1,
        soloMax: 5,
        groupMin: 1,
        groupMax: 8,
        monsters: "Rats, bats, spiders, beetles, skeletons, SK trainees",
        notes: "Night Terror (lvl 8) can spawn at night.",
        x: 310,
        y: 600,
      },
      {
        id: "nh-boatyard",
        name: "Garrison Boatyard",
        soloMin: 1,
        soloMax: 5,
        groupMin: 1,
        groupMax: 5,
        monsters: "Rats",
        notes: "",
        x: 185,
        y: 575,
      },
      {
        id: "nh-croc-hatchlings",
        name: "West gate shoreline crocs",
        soloMin: 4,
        soloMax: 7,
        groupMin: 3,
        groupMax: 6,
        monsters: "Crocodile hatchlings",
        notes: "Non-hostile. Continues into Shaded Dunes. Named Snar the Egg Collector can spawn.",
        x: 175,
        y: 530,
      },
      {
        id: "nh-twilight-goblins",
        name: "Twilight Harbor goblins",
        soloMin: 13,
        soloMax: 15,
        groupMin: 8,
        groupMax: 12,
        monsters: "Goblins",
        notes: "West of Twilight Harbor by the cranes. Social, no faction hit. Overlooked camp.",
        x: 195,
        y: 545,
      },
      {
        id: "nh-graveyard",
        name: "City graveyard",
        soloMin: 12,
        soloMax: 16,
        groupMin: 10,
        groupMax: 14,
        monsters: "Undead",
        notes: "Above the necro area. Need a key (quest). They come out at night.",
        x: 305,
        y: 575,
      },
    ],
  },
  {
    id: "sungreet-strand",
    name: "Sungreet Strand",
    regionId: "szuur",
    kind: "outdoor",
    layer: "surface",
    levelMin: 4,
    levelMax: 32,
    adjacent: ["night-harbor", "glass-flats", "grain-cellar", "tel-ekir"],
    description:
      "Farms, beach, and Ashira tents north of Night Harbor. Main overland path toward Glass Flats.",
    path: "M 148 360 L 230 300 L 330 292 L 372 400 L 338 492 L 248 478 L 168 508 L 140 450 Z",
    labelX: 240,
    labelY: 400,
    camps: [
      {
        id: "ss-ashira-tents",
        name: "Ashira tent camps",
        soloMin: 5,
        soloMax: 10,
        groupMin: 4,
        groupMax: 8,
        monsters: "Ashira",
        notes: "Tents just into the strand. Groups can start around 4–5.",
        x: 220,
        y: 430,
      },
      {
        id: "ss-beach-thugs",
        name: "Beach thugs & acolytes",
        soloMin: 12,
        soloMax: 16,
        groupMin: 8,
        groupMax: 12,
        monsters: "Thugs, acolytes",
        notes: "Past the Ashira camps. High damage — tank and healer recommended.",
        x: 185,
        y: 390,
      },
      {
        id: "ss-quarry-cinder",
        name: "Quarry — cinder workers",
        soloMin: 20,
        soloMax: 24,
        groupMin: 16,
        groupMax: 20,
        monsters: "Cinder workers / beetles",
        notes: "Loot feeds Cinder Beetle armor quests.",
        x: 300,
        y: 360,
      },
      {
        id: "ss-quarry-goblins",
        name: "Quarry — goblins",
        soloMin: 22,
        soloMax: 28,
        groupMin: 18,
        groupMax: 23,
        monsters: "Goblins",
        notes: "Two named, big pulls, casters. Dangerous.",
        x: 325,
        y: 345,
      },
      {
        id: "ss-ashira-flats",
        name: "Ashira by Glass Flats line",
        soloMin: 21,
        soloMax: 26,
        groupMin: 18,
        groupMax: 23,
        monsters: "Ashira",
        notes: "Near the water at the Glass Flats zoneline.",
        x: 280,
        y: 310,
      },
      {
        id: "ss-pirates",
        name: "Pirates (fourth agricole)",
        soloMin: 26,
        soloMax: 32,
        groupMin: 22,
        groupMax: 28,
        monsters: "Pirates, hired trackers",
        notes: "Fourth farm building. Pair with Grain Cellar.",
        x: 260,
        y: 350,
      },
    ],
  },
  {
    id: "shaded-dunes",
    name: "Shaded Dunes",
    regionId: "szuur",
    kind: "outdoor",
    layer: "surface",
    levelMin: 4,
    levelMax: 20,
    adjacent: [
      "night-harbor",
      "tel-ekir",
      "fallen-pass",
      "ancient-crypt",
      "infested-crypt",
      "caves-of-irem",
    ],
    description:
      "Dunes east of the harbor. Ashira camps, crocs, smugglers who turn wererat at night, and the road to Fallen Pass.",
    path: "M 338 492 L 372 400 L 520 410 L 610 470 L 590 590 L 470 650 L 368 548 Z",
    labelX: 470,
    labelY: 520,
    camps: [
      {
        id: "sd-ashira-telekir",
        name: "Ashira near Tel Ekir line",
        soloMin: 6,
        soloMax: 10,
        groupMin: 6,
        groupMax: 10,
        monsters: "Ashira",
        notes: "Multiple camps with a convenient zoneline evac.",
        x: 560,
        y: 560,
      },
      {
        id: "sd-smugglers",
        name: "Smugglers / wererat camp",
        soloMin: 8,
        soloMax: 12,
        groupMin: 6,
        groupMax: 10,
        monsters: "Smugglers, wererats, nearby undead",
        notes: "Far down the coast toward the glowing green castle. Smugglers become wererats at night. Named Toma the Two-Faced.",
        x: 520,
        y: 600,
      },
      {
        id: "sd-undead-highway",
        name: "Undead highway",
        soloMin: 8,
        soloMax: 10,
        groupMin: 6,
        groupMax: 10,
        monsters: "Skeletons, zombies",
        notes: "East down the coast with the smugglers. Holds several groups.",
        x: 500,
        y: 575,
      },
      {
        id: "sd-crocs",
        name: "Coastal crocs & caimans",
        soloMin: 5,
        soloMax: 8,
        groupMin: 4,
        groupMax: 8,
        monsters: "Crocodiles, caimans",
        notes: "Watch for Chompers (~16) the named giant croc.",
        x: 400,
        y: 560,
      },
    ],
  },
  {
    id: "glass-flats",
    name: "Glass Flats",
    regionId: "szuur",
    kind: "outdoor",
    layer: "surface",
    levelMin: 18,
    levelMax: 60,
    adjacent: ["sungreet-strand", "vale-of-zintar"],
    description:
      "Dangerous salt flats north of the Sungreet farms. Goblins, vipers, beetles, and later cultist towers.",
    path: "M 230 300 L 330 210 L 500 198 L 575 285 L 520 410 L 372 400 L 330 292 Z",
    labelX: 400,
    labelY: 300,
    camps: [
      {
        id: "gf-goblin-left",
        name: "Goblin camp (left from SS)",
        soloMin: 18,
        soloMax: 22,
        groupMin: 16,
        groupMax: 20,
        monsters: "Goblins",
        notes: "Turn left after zoning in from Sungreet Strand. Named Baron Bigtent in the zone.",
        x: 340,
        y: 340,
      },
      {
        id: "gf-beach-vipers",
        name: "Beach vipers & beetles",
        soloMin: 24,
        soloMax: 28,
        groupMin: 20,
        groupMax: 25,
        monsters: "Szuurian vipers, beetles",
        notes: "Straight ahead after entering. Roaming named 30+.",
        x: 300,
        y: 280,
      },
      {
        id: "gf-outer-cultists",
        name: "Outer cultists",
        soloMin: 46,
        soloMax: 52,
        groupMin: 42,
        groupMax: 48,
        monsters: "Cultists",
        notes: "High-level camps.",
        x: 460,
        y: 260,
      },
      {
        id: "gf-sw-cultists",
        name: "Southwest cultists",
        soloMin: 48,
        soloMax: 54,
        groupMin: 45,
        groupMax: 50,
        monsters: "Cultists",
        notes: "",
        x: 360,
        y: 250,
      },
      {
        id: "gf-undead-tower",
        name: "Camps around undead tower",
        soloMin: 52,
        soloMax: 60,
        groupMin: 51,
        groupMax: 60,
        monsters: "Undead, cultists",
        notes: "Endgame flats camps.",
        x: 500,
        y: 230,
      },
    ],
  },
  {
    id: "fallen-pass",
    name: "Fallen Pass",
    regionId: "szuur",
    kind: "outdoor",
    layer: "surface",
    levelMin: 16,
    levelMax: 60,
    adjacent: ["shaded-dunes", "vale-of-zintar", "fallen-watch"],
    description:
      "Canyon road from the dunes toward Zintar. Skeletons in the pit, ghouls up the ramp, plagueborn and Skri'Var rats later.",
    path: "M 520 410 L 575 285 L 690 300 L 760 390 L 720 500 L 610 470 Z",
    labelX: 640,
    labelY: 400,
    camps: [
      {
        id: "fp-pit-skeletons",
        name: "Pit dusty skeletons",
        soloMin: 17,
        soloMax: 20,
        groupMin: 15,
        groupMax: 19,
        monsters: "Dusty skeletons (16–19)",
        notes: "Just inside the zone — don't go up the ramp. Easy singles along the wall.",
        x: 560,
        y: 440,
      },
      {
        id: "fp-pit-beetles",
        name: "Pit bone carver beetles",
        soloMin: 25,
        soloMax: 27,
        groupMin: 20,
        groupMax: 25,
        monsters: "Bone carver beetles",
        notes: "Named Necroferius.",
        x: 580,
        y: 455,
      },
      {
        id: "fp-ramp-ghouls",
        name: "Ramp skeletons & ghouls",
        soloMin: 26,
        soloMax: 28,
        groupMin: 20,
        groupMax: 25,
        monsters: "Skeletons, ghouls",
        notes: "Up the ramp to the left. Ghoul adepts nuke ~200 blaze — interrupt. Great xp.",
        x: 620,
        y: 390,
      },
      {
        id: "fp-necro-cave",
        name: "Necro cave (canyon bank)",
        soloMin: 28,
        soloMax: 32,
        groupMin: 20,
        groupMax: 25,
        monsters: "Undead rats, fallen adventurers",
        notes: "Best exp/kill in FP, fewer mobs so worse exp/hour.",
        x: 600,
        y: 420,
      },
      {
        id: "fp-plagueborn",
        name: "Plagueborn undead",
        soloMin: 36,
        soloMax: 42,
        groupMin: 30,
        groupMax: 35,
        monsters: "Plagueborn undead",
        notes: "Ramp down on the far cliffs. Restless parade fights plagueborn at night. Constable patrols are higher.",
        x: 680,
        y: 360,
      },
      {
        id: "fp-skrivar",
        name: "Skri'Var rat camps",
        soloMin: 38,
        soloMax: 44,
        groupMin: 34,
        groupMax: 38,
        monsters: "Skri'Var rats",
        notes: "NE past stables through the mountains. Many named. Heavily camped.",
        x: 720,
        y: 350,
      },
      {
        id: "fp-elder-drakes",
        name: "Elder drakes",
        soloMin: 50,
        soloMax: 56,
        groupMin: 45,
        groupMax: 52,
        monsters: "Plagueborn elder drakes",
        notes: "",
        x: 700,
        y: 320,
      },
      {
        id: "fp-saman-stables",
        name: "Lower Saman / stables",
        soloMin: 57,
        soloMax: 60,
        groupMin: 51,
        groupMax: 60,
        monsters: "Undead, plagueborn ghouls",
        notes: "",
        x: 740,
        y: 380,
      },
    ],
  },
  {
    id: "vale-of-zintar",
    name: "Vale of Zintar",
    regionId: "szuur",
    kind: "outdoor",
    layer: "surface",
    levelMin: 22,
    levelMax: 60,
    adjacent: ["fallen-pass", "glass-flats", "keepers-bight"],
    description:
      "Corrupted vale under a floating castle. Bridge between desert Szuur and green Calafrey.",
    path: "M 575 285 L 500 198 L 620 155 L 760 175 L 790 275 L 690 300 Z",
    labelX: 660,
    labelY: 235,
    camps: [
      {
        id: "vz-corrupted-ashira",
        name: "Corrupted Ashira (lake tents)",
        soloMin: 30,
        soloMax: 32,
        groupMin: 22,
        groupMax: 28,
        monsters: "Corrupted Ashira hunters",
        notes: "Hug right wall from the pass. Tents by a lake beneath the floating castle. Strong vendor loot.",
        x: 640,
        y: 260,
      },
      {
        id: "vz-dustrend-orcs",
        name: "Dustrend orc camp",
        soloMin: 32,
        soloMax: 35,
        groupMin: 26,
        groupMax: 30,
        monsters: "Dustrend orcs",
        notes: "Near Fallen Pass entrance, northwest. Better exp than corrupted Ashira, worse loot.",
        x: 600,
        y: 270,
      },
      {
        id: "vz-burrowers",
        name: "Tomb burrower camp",
        soloMin: 32,
        soloMax: 39,
        groupMin: 32,
        groupMax: 38,
        monsters: "Tomb burrowers (giant / elder / ancient), silver & gold devourers",
        notes: "Not KoS but social. They dig away and reappear. Watch adds. Higher burrowers ~36–39.",
        x: 700,
        y: 220,
      },
      {
        id: "vz-sand-giants",
        name: "Sand giant city",
        soloMin: null,
        soloMax: null,
        groupMin: 55,
        groupMax: 60,
        monsters: "Sand giants and other giants",
        notes: "Can't solo. Name of the city still fuzzy on the wiki.",
        x: 740,
        y: 200,
      },
    ],
  },
  {
    id: "fallen-watch",
    name: "Fallen Watch",
    regionId: "szuur",
    kind: "outdoor",
    layer: "surface",
    levelMin: 20,
    levelMax: 45,
    adjacent: ["fallen-pass"],
    description: "Watch-fort country off Fallen Pass. Sparse public camp notes — add your own.",
    path: "M 760 390 L 790 275 L 900 290 L 940 390 L 880 470 L 720 500 Z",
    labelX: 840,
    labelY: 380,
    camps: [],
  },
  {
    id: "tel-ekir",
    name: "Tel Ekir",
    regionId: "szuur",
    kind: "dungeon",
    layer: "surface",
    levelMin: 9,
    levelMax: 20,
    adjacent: ["shaded-dunes", "sungreet-strand"],
    description: "Ashira and Bloodynose goblin dungeon off the dunes / strand.",
    path: "M 590 590 L 610 470 L 720 500 L 740 610 L 680 680 L 560 670 Z",
    labelX: 650,
    labelY: 590,
    camps: [
      {
        id: "te-ashira-entrance",
        name: "Ashira entrance",
        soloMin: 12,
        soloMax: 18,
        groupMin: 9,
        groupMax: 16,
        monsters: "Ashira",
        notes: "Four named. Alpha camp is higher.",
        x: 630,
        y: 540,
      },
      {
        id: "te-bloodynose",
        name: "Bloodynose goblins",
        soloMin: 17,
        soloMax: 22,
        groupMin: 10,
        groupMax: 15,
        monsters: "Bloodynose goblins",
        notes: "Tank and healer needed.",
        x: 670,
        y: 610,
      },
    ],
  },
  {
    id: "tomb-wyrmsbane",
    name: "Tomb of the Last Wyrmsbane",
    regionId: "szuur",
    kind: "dungeon",
    layer: "surface",
    levelMin: 4,
    levelMax: 20,
    adjacent: ["night-harbor"],
    description: "Starter dungeon off Night Harbor. Increasingly hard undead camps and solid gear.",
    path: "M 168 612 L 248 648 L 260 740 L 170 760 L 120 700 L 148 612 Z",
    labelX: 195,
    labelY: 700,
    camps: [
      {
        id: "tw-entrance",
        name: "Entrance undead",
        soloMin: 8,
        soloMax: 14,
        groupMin: 4,
        groupMax: 14,
        monsters: "Undead",
        notes: "Can grind a long time as camps get harder. Good gear drops.",
        x: 200,
        y: 670,
      },
    ],
  },
  {
    id: "shallow-shoals",
    name: "Shallow Shoals",
    regionId: "szuur",
    kind: "ocean",
    layer: "surface",
    levelMin: 30,
    levelMax: 40,
    adjacent: ["keepers-bight"],
    description: "Island waters and player housing. Boat dock at Zaedin's Landing.",
    path: "M 70 210 C 90 170 150 155 200 175 C 230 230 210 300 150 330 C 90 320 55 260 70 210 Z",
    labelX: 140,
    labelY: 240,
    camps: [
      {
        id: "shoals-basilisks",
        name: "Basilisk island",
        soloMin: 38,
        soloMax: 44,
        groupMin: 30,
        groupMax: 35,
        monsters: "Basilisks",
        notes: "Island across from the boat dock at Zaedin's Landing. Good iron / some gold mining.",
        x: 130,
        y: 250,
      },
    ],
  },
  {
    id: "ancient-crypt",
    name: "Ancient Crypt",
    regionId: "szuur",
    kind: "dungeon",
    layer: "surface",
    levelMin: 13,
    levelMax: 21,
    adjacent: ["shaded-dunes"],
    description: "Undead crypt off Shaded Dunes. Kitchen, commander, library, researcher wings.",
    path: "M 470 650 L 530 640 L 545 700 L 490 720 L 450 690 Z",
    labelX: 500,
    labelY: 680,
    camps: [
      {
        id: "ac-wings",
        name: "Entrance through researcher",
        soloMin: 21,
        soloMax: 26,
        groupMin: 13,
        groupMax: 18,
        monsters: "Skeletons",
        notes: "Entrance, kitchen, commander, library, researcher. Tank and healer.",
        x: 500,
        y: 675,
      },
    ],
  },
  {
    id: "infested-crypt",
    name: "Infested Crypt",
    regionId: "szuur",
    kind: "dungeon",
    layer: "surface",
    levelMin: 10,
    levelMax: 20,
    adjacent: ["shaded-dunes"],
    description: "Second crypt off Shaded Dunes. Add camps as you map it.",
    path: "M 530 640 L 590 630 L 600 685 L 545 700 Z",
    labelX: 565,
    labelY: 665,
    camps: [],
  },
  {
    id: "grain-cellar",
    name: "Grain Cellar",
    regionId: "szuur",
    kind: "dungeon",
    layer: "surface",
    levelMin: 22,
    levelMax: 35,
    adjacent: ["sungreet-strand"],
    description: "Secret cellar under the third agricole building in Sungreet Strand. Double-click the wall.",
    path: "M 250 318 L 300 310 L 312 355 L 262 365 Z",
    labelX: 282,
    labelY: 338,
    camps: [
      {
        id: "gc-undead-cultists",
        name: "Cellar undead & cultists",
        soloMin: 30,
        soloMax: 35,
        groupMin: 29,
        groupMax: 35,
        monsters: "Undead, cultists",
        notes: "Full of casters. Secret zone — double-click a wall in the third farm building.",
        x: 280,
        y: 340,
      },
    ],
  },
  {
    id: "grimtide-sanctum",
    name: "Grimtide Sanctum",
    regionId: "szuur",
    kind: "dungeon",
    layer: "surface",
    levelMin: 15,
    levelMax: 30,
    adjacent: ["shaded-dunes"],
    description: "Crumbling cavern. Exodus lands above the zone-in tunnel.",
    path: "M 400 630 L 455 620 L 465 665 L 410 675 Z",
    labelX: 432,
    labelY: 648,
    camps: [],
  },
  {
    id: "night-harbor-sewers",
    name: "Night Harbor Sewers",
    regionId: "szuur",
    kind: "dungeon",
    layer: "surface",
    levelMin: 5,
    levelMax: 20,
    adjacent: ["night-harbor"],
    description: "Under the city. Exodus location still fuzzy on community maps.",
    path: "M 300 618 L 340 610 L 348 650 L 308 658 Z",
    labelX: 325,
    labelY: 635,
    camps: [],
  },
  {
    id: "keepers-bight",
    name: "Keeper's Bight",
    regionId: "calafrey",
    kind: "outdoor",
    layer: "surface",
    levelMin: 5,
    levelMax: 40,
    adjacent: ["evershade-weald", "scarwood", "vale-of-zintar", "blacktide-bay", "shallow-shoals"],
    description:
      "Coastal wilds of Calafrey. Wolves and wasps for low levels, poacher camps in the high 20s.",
    path: "M 500 198 L 470 130 L 620 95 L 780 115 L 790 175 L 760 175 L 620 155 Z",
    labelX: 640,
    labelY: 145,
    camps: [
      {
        id: "kb-wildlife",
        name: "Timber wolves & asps",
        soloMin: 5,
        soloMax: 10,
        groupMin: 5,
        groupMax: 10,
        monsters: "Timber wolves, bight asps, wasp scouts",
        notes: "Low-level Calafrey yard trash.",
        x: 560,
        y: 160,
      },
      {
        id: "kb-poachers",
        name: "Poacher camps",
        soloMin: 32,
        soloMax: 38,
        groupMin: 28,
        groupMax: 35,
        monsters: "Poachers (named Tolan, Garrus ~35)",
        notes: "Named drop tunic, legs, boots, dagger for undead NPC in the bear cave. Skinning daggers for wis bracer.",
        x: 700,
        y: 140,
      },
    ],
  },
  {
    id: "evershade-weald",
    name: "Evershade Weald",
    regionId: "calafrey",
    kind: "outdoor",
    layer: "surface",
    start: true,
    levelMin: 1,
    levelMax: 15,
    adjacent: ["keepers-bight", "faelindral", "glinting-hollow", "blacktide-bay"],
    description:
      "Wood Elf and Halfling starting forest. Faelindral, the City in the Trees, sits here.",
    path: "M 470 130 L 455 48 L 700 40 L 820 70 L 800 130 L 780 115 L 620 95 Z",
    labelX: 640,
    labelY: 80,
    camps: [
      {
        id: "ew-starter",
        name: "Faelindral lift yards",
        soloMin: 1,
        soloMax: 5,
        groupMin: 1,
        groupMax: 5,
        monsters: "Wasps, spiders, rats, bats, drakelings, dryads, black widows",
        notes: "Main lift starting area.",
        x: 620,
        y: 95,
      },
      {
        id: "ew-wasp-ruins",
        name: "Wasp ruins",
        soloMin: 3,
        soloMax: 8,
        groupMin: 2,
        groupMax: 6,
        monsters: "Wasp workers",
        notes: "Neutral but social aggro. West along the main walkways.",
        x: 520,
        y: 90,
      },
      {
        id: "ew-scout-camp",
        name: "Fellstone orc scout camp",
        soloMin: 3,
        soloMax: 8,
        groupMin: 2,
        groupMax: 6,
        monsters: "Fellstone orc scouts",
        notes: "Fork in the main paths — if you see spiders you're close. 3 orcs + roamer + tree spawn. Unintelligible notes turn-in. Named spawn.",
        x: 700,
        y: 85,
      },
      {
        id: "ew-wolves",
        name: "Hillside wolves",
        soloMin: 8,
        soloMax: 12,
        groupMin: 6,
        groupMax: 10,
        monsters: "Wolves",
        notes: "West after the hillside path near the Druid Ring. Named wolf. Great leather.",
        x: 500,
        y: 70,
      },
    ],
  },
  {
    id: "faelindral",
    name: "Faelindral",
    regionId: "calafrey",
    kind: "city",
    layer: "surface",
    start: true,
    levelMin: 1,
    levelMax: 10,
    adjacent: ["evershade-weald"],
    description: "City in the Trees. Wood Elf and Halfling starting city inside Evershade Weald.",
    path: "M 600 55 L 655 48 L 668 85 L 612 92 Z",
    labelX: 634,
    labelY: 68,
    camps: [],
  },
  {
    id: "scarwood",
    name: "Scarwood",
    regionId: "calafrey",
    kind: "outdoor",
    layer: "surface",
    levelMin: 20,
    levelMax: 40,
    adjacent: ["keepers-bight", "sunken-resort"],
    description: "Scarred woodland east of the Bight. River island bandits in the mid 20s.",
    path: "M 780 115 L 800 130 L 920 140 L 1020 210 L 980 330 L 860 340 L 790 275 L 760 175 Z",
    labelX: 900,
    labelY: 230,
    camps: [
      {
        id: "sw-bandits",
        name: "River island bandits",
        soloMin: 27,
        soloMax: 32,
        groupMin: 22,
        groupMax: 27,
        monsters: "Bandits (2 named)",
        notes: "Center of the zone, island in the river. May be thin for a full group.",
        x: 880,
        y: 240,
      },
    ],
  },
  {
    id: "blacktide-bay",
    name: "Blacktide Bay",
    regionId: "calafrey",
    kind: "outdoor",
    layer: "surface",
    levelMin: 8,
    levelMax: 25,
    adjacent: ["evershade-weald", "keepers-bight"],
    description: "Western Calafrey coast. Exodus lands at the Evershade Weald line.",
    path: "M 300 90 L 455 48 L 470 130 L 400 175 L 280 160 Z",
    labelX: 370,
    labelY: 115,
    camps: [],
  },
  {
    id: "glinting-hollow",
    name: "Glinting Hollow",
    regionId: "calafrey",
    kind: "dungeon",
    layer: "surface",
    levelMin: 10,
    levelMax: 25,
    adjacent: ["evershade-weald"],
    description: "Ruins with Lyssindra. Zone-in is in the ruins.",
    path: "M 820 70 L 900 60 L 930 110 L 860 130 L 800 130 Z",
    labelX: 870,
    labelY: 95,
    camps: [],
  },
  {
    id: "sunken-resort",
    name: "Sunken Resort",
    regionId: "calafrey",
    kind: "dungeon",
    layer: "surface",
    levelMin: 20,
    levelMax: 35,
    adjacent: ["scarwood"],
    description: "Off Scarwood. Exodus at the Scarwood line.",
    path: "M 980 330 L 1020 210 L 1100 250 L 1080 360 L 1000 380 Z",
    labelX: 1045,
    labelY: 310,
    camps: [],
  },
  {
    id: "underdocks",
    name: "The Underdocks",
    regionId: "deep",
    kind: "city",
    layer: "deep",
    start: true,
    levelMin: 1,
    levelMax: 15,
    adjacent: ["night-harbor", "caves-of-irem", "great-cavern-sea"],
    description:
      "Seedy underground port far below Night Harbor. Conduit between the surface and the Deep. Neutral and evil start here.",
    path: "M 190 500 L 280 480 L 350 530 L 320 620 L 220 640 L 170 580 Z",
    labelX: 260,
    labelY: 555,
    camps: [
      {
        id: "ud-starter",
        name: "Underdock yards",
        soloMin: 1,
        soloMax: 8,
        groupMin: 1,
        groupMax: 8,
        monsters: "Rats, bats, dock vermin",
        notes: "Starting city for some neutral/evil combos. Add camps as you learn them.",
        x: 250,
        y: 560,
      },
    ],
  },
  {
    id: "caves-of-irem",
    name: "Caves of Irem",
    regionId: "deep",
    kind: "dungeon",
    layer: "deep",
    levelMin: 8,
    levelMax: 25,
    adjacent: ["shaded-dunes", "underdocks", "great-cavern-sea"],
    description: "Deep caves reached from Shaded Dunes. First stretch of Descent into the Deep.",
    path: "M 360 540 L 500 500 L 560 580 L 500 660 L 380 650 Z",
    labelX: 460,
    labelY: 580,
    camps: [],
  },
  {
    id: "great-cavern-sea",
    name: "Great Cavern Sea",
    regionId: "deep",
    kind: "ocean",
    layer: "deep",
    levelMin: 15,
    levelMax: 40,
    adjacent: ["underdocks", "caves-of-irem", "rothold", "ail-vorith"],
    description: "An inland sea in the dark. Connects Deep regions under Szuur and Calafrey.",
    path: "M 280 430 C 360 360 520 340 680 380 C 780 450 740 560 600 600 C 450 630 300 560 280 430 Z",
    labelX: 520,
    labelY: 480,
    camps: [],
  },
  {
    id: "rothold",
    name: "Rothold",
    regionId: "deep",
    kind: "dungeon",
    layer: "deep",
    levelMin: 20,
    levelMax: 45,
    adjacent: ["great-cavern-sea"],
    description: "Ruins of Roothold Keep in the Deep.",
    path: "M 640 520 L 760 500 L 800 600 L 700 650 L 620 600 Z",
    labelX: 710,
    labelY: 575,
    camps: [],
  },
  {
    id: "blind-midden",
    name: "The Blind Midden",
    regionId: "deep",
    kind: "dungeon",
    layer: "deep",
    levelMin: 25,
    levelMax: 50,
    adjacent: ["ail-vorith"],
    description: "New dungeon near the Deep Elf city of Ail'vorith.",
    path: "M 860 220 L 980 200 L 1020 300 L 920 340 L 840 290 Z",
    labelX: 930,
    labelY: 265,
    camps: [],
  },
  {
    id: "ail-vorith",
    name: "Ail'vorith",
    regionId: "deep",
    kind: "city",
    layer: "deep",
    start: true,
    levelMin: 1,
    levelMax: 20,
    adjacent: ["blind-midden", "great-cavern-sea"],
    description:
      "Dark capital of the Deep Elves, beneath eastern Calafrey. Starting city for various evil race/faith/class combinations.",
    path: "M 880 90 L 1020 80 L 1080 180 L 980 220 L 860 180 Z",
    labelX: 970,
    labelY: 145,
    camps: [
      {
        id: "av-starter",
        name: "Ail'vorith yards",
        soloMin: 1,
        soloMax: 8,
        groupMin: 1,
        groupMax: 8,
        monsters: "Starter vermin and city trash",
        notes: "Deep Elf starting city. Add camps as you map them.",
        x: 960,
        y: 150,
      },
    ],
  },
];

module.exports = { regions, zones };
